### ISSUE TITLE
Included square font (square.ttf) has no lower case letters

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11679]
The font is otherwise nice, but an all-caps font isn't very playable in a game with case sensitive labels.

One or more of these fonts might make a good alternative:
http://fontstruct.com/gallery/tag/Roguelike

Here's an interesting article on the subject, with lots of screenshots but not a lot of useful links: http://www.gridsagegames.com/blog/2014/09/fonts-in-roguelikes/
##

**Comment by KA101** [comment]
Major issue is that we need the font's license to be compatible with CC-BY-SA 3.0 Unported; that's DDA's license.  Not every font works for that, I fear.  :-/

**Comment by sparr** [comment]
Would it make sense to just add small caps to square.ttf? I'm no font artist, but I can go in and shrink the lowercase glyps by 30% or so.

**Comment by KA101** [comment]
So far as I know, sure.  License compatible with CC-BY-SA means that it's OK to edit the font.

**Comment by drbig** [comment]
@sparr The square.ttf technically has lower and upper case letters (these are slightly 'boldier ') - but yeah it is definitely not perfect.

@KA101 Looking at http://fontstruct.com/gallery/tag/Roguelike some are CC-BY 3.0 Unported, others plain PD - I would assume both are compatible with CC-BY-SA 3.0 Unported?

**Comment by drbig** [comment]
[MapMaker](http://fontstruct.com/fontstructions/show/mapmaker_1) in action:

![MapMaker 14 pt](http://i.imgur.com/Vdtw7hO.png)

Looks square enough to me, and the exact license is `Creative Commons CC0 Public Domain Dedication` - I assume *this* is compatible.

**Comment by sparr** [comment]
that's pretty spiffy. I'll try playing with it and see how it fares.

PS: I think our square font might not have line drawing characters in it? fontforge can't find them, if it does, and it looks like it just falls back to some standard system font.

**Comment by BevapDin** [comment]
Line drawing is always done through `draw_ascii_lines`, it never uses the font data.

**Comment by sparr** [comment]
I think draw_ascii_lines is only used in sdl/tiles mode.

**Comment by BevapDin** [comment]
Yes. But this issue applies to the tiles/wincurses version anyway. The ncurses version does not have a font-setting, the font of the terminal is used there, which is not configurable by the game.

Wincurses is a bit special, it uses the font from the configuration, but it, too, has the special code that draws lines manually and does not use the font for this, it has essentially the same code as in `draw_ascii_lines`.

**Comment by sparr** [comment]
I'm using the included font in my terminal. At least one other person on IRC is doing the same.

**Comment by BevapDin** [comment]
What does "my terminal" mean? Does it mean your terminal emulator (http://en.wikipedia.org/wiki/Terminal_emulator), e.g xterm, konsole (KDE), putty, Win32 console etc. - those programs ere configured separately from cataclysm (you might be able to configure them to use any font you want). In that case, the font data of the terminal emulator is used and cataclysm does not draw anything itself. The line drawings are send to the terminal emulator as Unicode/ASCII characters, what the terminal emulator does with them is its own thing.

Otherwise, if you mean the wincurses (which is merely a terminal emulator on its own) or the SDL build (any OS), the font from the configuration file (config/fonts.json) is used, except the line drawing is done manually and ignores the font data.

**Comment by sparr** [comment]
I mean all of the above? If the font doesn't have line drawing characters in it, then "xterm, konsole (KDE), putty, Win32 console etc" are all going to fail to load those nonexistent line drawing characters.

My obvservation that the characters/glyphs are missing is independent of any specific place to use the font.

**Comment by BevapDin** [comment]
> My obvservation that the characters/glyphs are missing is independent of any specific place to use the font.

You are correct. I didn't expect you to use the included font outside of the games own configuration where this problem wouldn't appear that easy. :+1:

**Comment by KA101** [comment]
I merged the customized small-caps Square earlier; if others have desired fonts, PR 'em and we'll make it happen.

**Comment by sparr** [comment]
MapMaker is a big heavy-stroked, and still doesn't contain box drawing characters. Its lowercase letters are better than Square's [lack of them]. I might try to add box characters to MapMaker? If no one can find any other square CC/PD font we could use?

**Comment by KA101** [comment]
> Its lowercase letters are better than Square's [lack of them]

We now have a square-small-caps font included in latest experimental, as I recall.  Am I, who don't actually like square fonts and wasn't sure how best to configure it, the only one who tried it?

**Comment by sparr** [comment]
@KA101 I'm the one who submitted that :p I've been using it since I submitted the PR. It's not as distinguishable as I'd hoped, because the big and small letters don't always appear adjacent to each other.

Same problem with O and o in many fonts, but much worse for it to affect all the letters.

I'll submit a PR for MapMaker, with or without the addition of line drawing characters, eventually.

**Comment by drbig** [comment]
@sparr What do you mean by MapMaker not having line drawing characters? It seems to work fine with e.g. mc in rxvt that does use lines, arrows etc. Am I missing something here?

**Comment by sparr** [comment]
@drbig my guess is that your terminal, like mine, falls back to another font, or even has logic for "drawing" the lines, for fonts that don't have line/box drawing characters. If you open the TTF in fontforge or birdfont or your font editor of choice, you'll find that it has very few glyphs outside of basic 7-bit ASCII.

**Comment by drbig** [comment]
Yeah, I was thinking that might be the case :/

**Comment by kevingranade** [comment]
Our license is precisely cc-by-sa 3.0 unported, so we're definitely
compatable with the mentioned font.
AFAIK the only cc we are not ok with is either NC or ND, everything else is
fine.

**Comment by Leland** [comment]
Closing - I believe the current game no longer suffers from this.
