### ISSUE TITLE
Acetylene torches spawn without welding tanks

### ISSUE THREAD

**Issue by 321nick** [CleverRaven/Cataclysm-DDA#16562]
When going into garages, acetylene torches will spawn, but no welding tanks, making them useless. im playing with 10x item spawn, so if it cant be due too rarity. im using build 4816 .

**Comment by mugling** [comment]
I think this is fixed in `master`. Can anyone else confirm?

**Comment by 321nick** [comment]
im certain it isnt, im using the latest build, and i have 10x item spawn, so im like, 99% sure it isnt fixed yet

**Comment by Mshock777** [comment]
You need to add `magazine` setting to item groups with oxy torch.

**Comment by mugling** [comment]
`tools_mechanic` sets `ammo`. If that doesn't result in an acetylene tank spawning that's a separate bug and should be fixed as opposed to also specifying `magazine`

**Comment by Mshock777** [comment]
Isn't this the way it supposed to be? That why we always set `magazine` for guns.

**Comment by mugling** [comment]
Setting `ammo` should create the default magazine if necessary

**Comment by Mshock777** [comment]
Sorry, looking into locations.json gave me an impression it was mandatory.

**Comment by mugling** [comment]
Can reproduce, problem is there are additional spawns for `oxy_torch` other than just `tools_mechanics`
