### ISSUE TITLE
[5071] "Filthy Gear" morale debuff stays even after filthy clothes are taken off

### ISSUE THREAD

**Issue by Vidiveni** [CleverRaven/Cataclysm-DDA#17245]
I briefly wore a filthy leather backpack in build 5071. The -6 morale seems to stay forever even after taking it off (tested several in-game days). I confirmed by getting completely [naked](http://i.imgur.com/zm1AeQW.jpg?1) and skipping a turn. 

Edit: Might and might not be fixed in pull request #17244, as I never did wash the item in question.

**Comment by BorkBorkGoesTheCode** [comment]
This may become an accidental feature if the player can take a bath.

**Comment by Night-Pryanik** [comment]
There was a bug prior to #17244 - washing filthy clothes when they are worn caused morale penalty to stay forever, and I couldn't find a way to remove these penalty.

**Comment by Rivet-the-Zombie** [comment]
@Night-Pryanik, please see my comment in https://github.com/CleverRaven/Cataclysm-DDA/issues/17247.

**Comment by Vidiveni** [comment]
This particular bug is unrelated to washed clothes.

**Comment by Coolthulhu** [comment]
Fixed by forced recalculation.

**Comment by codemime** [comment]
> Fixed by forced recalculation.

I suppose it's too early to close the issue. The forced recalculation wasn't a fix, it still shows a `debugmsg` indicating that the issue is here.

**Comment by Coolthulhu** [comment]
There were 2 bugs related to filthiness, both of them are fixed. What is left is bugged saves. Those will be fixed by recalculation, assuming it does its job.

**Comment by codemime** [comment]
Oh, okay. If bugged saves are the only cause of those bugs then it's fine.
