### ISSUE TITLE
Sinking doesn't work when you push a vehicle into deep water.

### ISSUE THREAD

**Issue by Oskar636** [CleverRaven/Cataclysm-DDA#19226]
As in the title, when you push a vehicle so all of it's parts are in deep water, it doesn't make it sink.
Probably needs a check for when all of the tiles on a vehicle are in water ( but I would argue for 50% or 75% of the tiles ). A bit tricky to reproduce with vehicles longer then 1 tile since pushing and pulling is really messy, but really easy to do with carts.

Build 5864 windows 64bit tiles

**Comment by mlangsdorf** [comment]
Confirmed. Not sure of the solution but I'd like to unify grabbed_vehicle_move with other pushed vehicle movement.

**Comment by Night-Pryanik** [comment]
Is this fixed by #27722?

**Comment by wapcaplet** [comment]
Still reproducible in 0.E-9681-g2cca4d658c. I can `G`rab the back of a bicycle and push it into deep water:

![image](https://user-images.githubusercontent.com/238395/108129509-87609f00-706b-11eb-95af-c2db1a8f3de4.png)

After letting go of the bicycle, it does not sink - and neither do I. My character can continue standing on the water, fully clothed and wearing a backpack, gaining athletics skill, and even reading a book, similar to the behavior described in #47305. My character does not sink until I move, and the bicycle does not sink until I move onto it.

**Comment by anoobindisguise** [comment]
This definitely doesn't happen anymore as of 2/27/22
