### ISSUE TITLE
Cities generate in swamps, but fail to place buildings

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#21497]
### Expected Behavior
One of:
* Cities do not generate in swamps
* Cities generated in swamps "dry" them

### Actual behavior
Cities generate in swamps and produce grids of roads, but fail to place buildings.

### Steps to reproduce the behavior
* Generate world with 16 city size, 0 city distance
* Find a city generated very close to a swamp

**Comment by Leland** [comment]
Screenshots from #21241:

>Map picture:
>
><img src="https://user-images.githubusercontent.com/24307650/27144972-d9c8442e-5101-11e7-8d70-174cb21c24a9.PNG" height="200px">
>
>Ground level picture:
>
><img src="https://user-images.githubusercontent.com/24307650/27145015-fe0ec9ac-5101-11e7-8486-dfac297c54c6.PNG" height="200px">
>
>
>Another weird but interesting mapgen problem:
>Ground view:
>
><img src="https://user-images.githubusercontent.com/24307650/27190993-66ff9f0a-51c4-11e7-9973-5bd25f6d47ba.PNG" height="200px">
>
>Map view (center of screen is gas station in the middle of the road... while in the middle of the water):
><img src="https://user-images.githubusercontent.com/24307650/27191031-87d48a2e-51c4-11e7-8659-0606e276094f.PNG" height="200px">
>
>
>
>
>Things are getting weird with mapgen recently, feel free to ask me to upload my save where all of these pictures came from. I saw the same gas station in another weird spot north of this one if it means anything. Im putting in a picture of that hotel that has a single road section that is literally in the middle of the river:
>(the map view for the hotel is above Treah's comment)
>
><img src="https://user-images.githubusercontent.com/24307650/27204484-76585e9e-51f9-11e7-8f9c-cacd28072f85.PNG" height="200px">
>
>
>

**Comment by pisskop** [comment]
Id like to say that having the game gen marshlands inside a city would be nice.  Bogs where development is so expensive that they dont happen outside real cities (that dont exist in cdda.  'cities' are really towns).

Some extra marshland not being citied is fine.

**Comment by Leland** [comment]
Seems to be unintentionally fixed by #21620. Roads now route around swamps and thus cities don't spawn within them. Spent some time warping around a map and couldn't find any instances of this where before they were fairly common.

**Comment by codemime** [comment]
Sorry, I have to step on your toes this time), the issue is still here (I'm quite sure of it). It's caused by the contradiction:
- city streets are straight. They simply follow the straight line while they can and don't try to avoid swamps (`land` location includes `forest_water`) .
- but adjacent houses check whether their terrain is `settings.default_oter `(never a swamp, usually `field`) and don't spawn on anything except it. They probably should spawn on `land` locations as well, but I'm reluctant to hardcode it.
