### ISSUE TITLE
Debug message when using the pot through the action menu

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#21772]
Trying to use pot to heat up the food through the action menu gives this error.

![123](https://user-images.githubusercontent.com/11132525/29996903-eb77c7ba-900f-11e7-8325-897ebd832fd3.PNG)

Using the pot through the `a`ctivate works as intended.

Windows XP SP3, tiles, 0.C-6731.

**Comment by BrokenAdmin** [comment]
Okay, why the hell are you using XP? But yes can confirm. It tries to consume nonexistent charges from the item. It's got something to do with the way the % menu uses stuff.

**Comment by BrokenAdmin** [comment]
@Night-Pryanik Confirmed tag please.

**Comment by Night-Pryanik** [comment]
> Okay, why the hell are you using XP?

Because my shitty notebook isn't powerful enough for modern Windows.

**Comment by OzoneH3** [comment]
It is fixed. Can't find the PR atm though, wasn't too long ago.

**Comment by Night-Pryanik** [comment]
Nah, it is still happening. Spawn pot, stay away from any source of fire and use the %-menu to heat up the food.

**Comment by Broken-Admin** [comment]
Wait, I'll contact KG later.

**Comment by OzoneH3** [comment]
My bad, uses the wrong menu .. I'll try whip something up.
