### ISSUE TITLE
OSX builds are failing

### ISSUE THREAD

**Issue by boydkr** [CleverRaven/Cataclysm-DDA#22970]
Game version: builds after #7121

Operating system: OSX

Tiles or curses: both

Mods active:

### Expected behavior

Compiles successfully

### Actual behavior

```
00:00:29.540 In file included from src/npc.cpp:1:
00:00:29.540 In file included from src/npc.h:5:
00:00:29.540 In file included from src/player.h:5:
00:00:29.540 In file included from src/character.h:5:
00:00:29.540 In file included from src/visitable.h:5:
00:00:29.540 In file included from /home/narc/osxcross/osxcross/target/bin/../SDK/MacOSX10.11.sdk/usr/include/c++/v1/functional:474:
00:00:29.540 /home/narc/osxcross/osxcross/target/bin/../SDK/MacOSX10.11.sdk/usr/include/c++/v1/type_traits:2348:38: error: incomplete type 'effects_map' used in type trait expression
00:00:29.540     : public integral_constant<bool, __is_constructible(_Tp, _Args...)>
00:00:29.540                                      ^
00:00:29.540 src/pimpl.h:23:76: note: in instantiation of template class 'std::__1::is_constructible<effects_map, const pimpl<effects_map> &>' requested here
00:00:29.540         template<typename ...Args, typename = typename std::enable_if<std::is_constructible<T, Args...>::value>::type>
00:00:29.540                                                                            ^
00:00:29.540 src/pimpl.h:24:18: note: in instantiation of default argument for 'pimpl<const pimpl<effects_map> &>' required here
00:00:29.540         explicit pimpl( Args && ... args ) : std::unique_ptr<T>( new T( std::forward<Args>( args )... ) ) { }
00:00:29.540                  ^~~~~
00:00:29.540 src/pimpl.h:20:7: note: while substituting deduced template arguments into function template 'pimpl' [with Args = <const pimpl<effects_map> &>, $1 = (no value)]
00:00:29.540 class pimpl : private std::unique_ptr<T>
00:00:29.540       ^
00:00:29.540 src/creature.h:20:7: note: forward declaration of 'effects_map'
00:00:29.540 class effects_map;
00:00:29.540       ^
00:00:29.540 In file included from src/npc.cpp:1:
00:00:29.540 In file included from src/npc.h:5:
00:00:29.540 In file included from src/player.h:5:
00:00:29.540 In file included from src/character.h:5:
00:00:29.540 In file included from src/visitable.h:5:
00:00:29.540 In file included from /home/narc/osxcross/osxcross/target/bin/../SDK/MacOSX10.11.sdk/usr/include/c++/v1/functional:474:
00:00:29.540 /home/narc/osxcross/osxcross/target/bin/../SDK/MacOSX10.11.sdk/usr/include/c++/v1/type_traits:2348:38: error: incomplete type 'effects_map' used in type trait expression
00:00:29.540     : public integral_constant<bool, __is_constructible(_Tp, _Args...)>
00:00:29.540                                      ^
00:00:29.540 src/pimpl.h:23:76: note: in instantiation of template class 'std::__1::is_constructible<effects_map, pimpl<effects_map> >' requested here
00:00:29.540         template<typename ...Args, typename = typename std::enable_if<std::is_constructible<T, Args...>::value>::type>
00:00:29.540                                                                            ^
00:00:29.540 src/pimpl.h:24:18: note: in instantiation of default argument for 'pimpl<pimpl<effects_map> >' required here
00:00:29.540         explicit pimpl( Args && ... args ) : std::unique_ptr<T>( new T( std::forward<Args>( args )... ) ) { }
00:00:29.540                  ^~~~~
00:00:29.540 src/pimpl.h:20:7: note: while substituting deduced template arguments into function template 'pimpl' [with Args = <pimpl<effects_map>>, $1 = (no value)]
00:00:29.540 class pimpl : private std::unique_ptr<T>
00:00:29.540       ^
00:00:29.540 src/creature.h:20:7: note: forward declaration of 'effects_map'
00:00:29.540 class effects_map;
00:00:29.540       ^
00:00:29.540 2 errors generated.
00:00:29.836 Makefile:732: recipe for target 'obj/tiles/npc.o' failed
```

### Steps to reproduce the behavior

automated build

**Comment by boydkr** [comment]
Based on the error message, suspect caused by #22917

**Comment by ZhilkinSerg** [comment]
Wasn't it fixed in #22955?

**Comment by boydkr** [comment]
Still failing as of build 7126, you can view the overall build status at 
http://gorgon.narc.ro:8080/job/Cataclysm-Matrix/ 

Click through to see the individual builds

**Comment by Leland** [comment]
Can confirm, will not build on my local.

**Comment by ZhilkinSerg** [comment]
Probably related - #23001

**Comment by Wulfe813** [comment]
Will changing the pimpl constructor to this fix it? (osxcross is giving me grief, and I don't have a Mac to test on anyways) It's just something I found in another project having a similar issue. Doesn't appear to implode the pimpl functionality, maybe it'll work?

`template<typename ...Args, typename = typename std::enable_if<std::is_constructible<T*, Args...>::value>::type>
explicit pimpl( Args && ... args ) : std::unique_ptr<T>( new T( std::forward<Args>( args )... ) ) { }`

**Comment by Wulfe813** [comment]
PR at #23048
