### ISSUE TITLE
Can't complete NPC Missions

### ISSUE THREAD

**Issue by Lazasar** [CleverRaven/Cataclysm-DDA#23824]
Game version: 7426

Operating system: Windows 10

Tiles or curses: Tiles

Mods active:
  "dda",
  "filthy_morale",
  "no_npc_food",
  "novitamins",
  "makeshift",
  "Medieval_Stuff",
  "More_Survival_Tools",
  "nw_pack",
  "alt_map_key",
  "npc_traits",
  "mxocosmetics",
  "mutant_npcs",
  "national_guard_camp",
  "Urban_Development",
  "boats",
  "deoxymod",
  "blazemod",
  "No_Fungi",
  "more_classes_scenarios",
  "no_reviving_zombies",
  "StatsThroughSkills"

### Expected behavior
When speaking with NPC after completing mission get the "I did it" or "here it is" message

### Actual behavior
So far I have tried the "Kill my Mom" and "Find weather patterns". I kill the mom, have the weather forecasts in my inventory and the NPC doesn't react accordingly when chatting with them.

Further, when the NPC dies, the mission remains in the log.

### Steps to reproduce the behavior
Get mission, do mission, speak to NPC

**Comment by FulcrumA** [comment]
NPCs are in general, despite being a feature full of ptoential and, I'd argue something that has the best potential to push game forward in scope from what we have now - are absolute mess, supposedly. They're riddled with bugs and problems and it's a consensus that repairing it would be like a bandaid on a gaping wound and the whole thing should be rebuilt.

That being said, the ticket certainly does report a bug. Personally, as I play with NPCs regularly, I found out that making NPC a companion, saving and closing the client etc may mess NPC quest status as if something regarding it wouldn't be saved (but that's pure guess on my part) though it's happening absolutely at random. Try to finish the quests during the same playsession you'll receive, don't talk with the NPC too much before then and generally - walk on eggshells around them.

**Comment by railmonkey** [comment]
Can confirm. This mostly happens after successfully convincing them to follow you before you finish the mission. They'll ask about the fetch quest item the first two times and then appear to forget about it entirely. Meanwhile, the mission remains in your log, and you'll have no choice but to fail it and accept the consequences (or debug the mission away).

**Comment by LOMS** [comment]
It looks like **sucessful** asking for training breaks mission completion.

**Comment by mlangsdorf** [comment]
Can't reproduce on latest experimental; I completed an inhaler mission, trained, and the mission was complete.  Repeated the process with a "kill zombie mom" mission without issue.

Please confirm on a recent experimental or I'll close this in a week or so.

**Comment by Lazasar** [comment]
I believe this was fixed some time ago.

**Comment by evil-toe-puppet** [comment]
Hi, 
the bug is still there so it seems. Had the same Issue. Im on verson: 0.D-5989-g03c9208

**Describe the bug / how to reproduce**
I talk to my start npc get the mission. then i got him to follow me and to share his skills. First 2-3 times i talk to him he resonse with the question about the mission an then stops asking about it an i get the normal NPC question for a NPC on garde. He stops asking about the mission probably after he teached me his skills the first time but im not sure. I did the mission (Kill Zombi Mom) but still no dialoge option to complete it.

Screenshots
![grafik](https://user-images.githubusercontent.com/53195771/62375739-35b2fb00-b53f-11e9-96ae-2e9f8f9f5b1b.png)
![grafik](https://user-images.githubusercontent.com/53195771/62375769-4b282500-b53f-11e9-8348-b8e5696130c4.png)

**Versions and configuration:**

    OS: Windows 7
    Game Version: 0.D-5989-g03c9208
    Graphics version: Tiles
    Mods loaded:

  "dda",
  "no_npc_food",
  "magiclysm",
  "stats_through_kills",
  "crt_expansion",
  "makeshift",
  "Tolerate_This",
  "growable-pots",
  "More_Survival_Tools",
  "nw_pack",
  "DinoMod",
  "modular_turrets",
  "Salvaged_Robots",
  "hydroponics",
  "MMA",
  "deoxymod"

**Comment by Berkyjay** [comment]
Can confirm, asking NPCs for skill training breaks the mission mechanics.
