### ISSUE TITLE
Separation of animal growth from monster evolution

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#24691]
Currently maturing of carrion eaters, domesticated poultry and other wild animals is dependant on mosnter evolution mechanism as per #23833. I'd like to request separation of it from above mechanics, making it time-related. Monster evolution was initially meant to be mechanic ramping up difficulty of creatures in the context of combat/avoidance. By comparison, aside from some pests, animal maturing feature mostly affects things like farming (ranching) and other such activities.

Settings of one aspect of the gameplay (combat) shouldn't affect other aspects detached from it. Making maturing of wild animals a separate value would allow adjustment of combat difficulty (or even turning off monster evolution off entirely) without affecting ranching, and vice versa.

**Comment by mlangsdorf** [comment]
```
int monster::next_upgrade_time() {
    if( type->age_grow > 0 ){
        return type->age_grow;
    }
    const int scaled_half_life = type->half_life * get_option<float>( "MONSTER_UPGRADE_FACTOR" );
    int day = scaled_half_life;

```
As far as I can tell, creatures have age_grow, monsters have half_lifes. age_grow isn't scaled to the monster evolution, but half_lifes are. Isn't your request the way the code already works?

**Comment by FulcrumA** [comment]
Supposedly, the thing is still based upon whether monster evolution is active. As per feature creator claim: "Disabling evolution should prevent animal growth at the moment " at the bottom of the linked ticket. This ticket in turn asks to separate them entirely, in hopes of possibilities such as disabling or adjustment of lengths of time/frequency for creatures changing in either of the features separately for each feature.

**Comment by mlangsdorf** [comment]
So this is not great.
```
bool monster::can_upgrade()
{
    return upgrades && get_option<float>( "MONSTER_UPGRADE_FACTOR" ) > 0.0;
}

void monster::try_upgrade( bool pin_time )
{
    if( !can_upgrade() ) {
        return;
    }
    if( upgrade_time < 0 ) {
        upgrade_time = next_upgrade_time();
        if( upgrade_time < 0 ) {
            return;
        }
        if( pin_time || type->age_grow > 0 ) {
            // offset by today, always true for growing creatures
            upgrade_time += current_day;
        }
    }
   ...
}
```

So animal upgrade time isn't affected by MONSTER UPGRADE FACTOR, except if MONSTER_UPGRADE_FACTOR = 0 then it's disabled entirely.

```
-    return upgrades && get_option<float>( "MONSTER_UPGRADE_FACTOR" ) > 0.0;
+    return upgrades && ( type->age_grow > 0 || get_option<float>( "MONSTER_UPGRADE_FACTOR" ) > 0.0 );
```
should fix it, though.

**Comment by Night-Pryanik** [comment]
Should this be closed after we removed the entire eggs spawn in #28304?

**Comment by FulcrumA** [comment]
Even without eggs the issue still exists in relation to maturation of livestock, for example.
