### ISSUE TITLE
Sound at ... has no description

### ISSUE THREAD

**Issue by SeelenJaegerTee** [CleverRaven/Cataclysm-DDA#27221]
**Describe the bug**  
When playing a music instrument the error appears:
An error has occurred! [...]
DEBUG: Sound at 63:60 has no description!
[...]
see attached debug log

**To Reproduce**  
Use debug menu to add a music instrument (tested with bone flute and accoustic guitar).
Play instrument.
Error appears.

**Expected behavior**  
No error should appear.

**Versions and configuration(please complete the following information):**
 - OS: compiled for linux with make -j4 NATIVE=linux64 RELEASE=1 TILES=1 LTO=1 ASTYLE=0 SOUND=1 LOCALIZE=0 LUA=1
 - Game Version: 0.C-35416-gda33751d35
 - Graphics version: Tiles
 - Mods loaded [e.g.dda, boats, hacktheplanet, StatsThroughSkills]

**Additional context**  
Log file [debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/2703462/debug.log)

PS: This bug must have snuck in somewhere after version 0.C-35880-g9c644303cd.
I compiled that version some days ago and there the error was not appearing.

**Comment by ZhilkinSerg** [comment]
Please confirm bug is resolved in latest version.

**Comment by SeelenJaegerTee** [comment]
Cloning right now.
Connection is somewhat slow so this may take a while to DL.

**Comment by SeelenJaegerTee** [comment]
Just finished building 0.C-35422-g9976671964.
Error still occurs
![screenshot from 2018-12-21 20-15-28](https://user-images.githubusercontent.com/39884350/50359558-7ab09100-055d-11e9-845d-7fb581821c72.png)
.

**Comment by ZhilkinSerg** [comment]
Thanks for checking.

**Comment by mlangsdorf** [comment]
Please copy the last 25 or so lines of your config/debug.log so I can find the errant sound.

**Comment by SeelenJaegerTee** [comment]
Attached you find a fresh debug log replicating the error (only 64 lines). All I did was loading a save with active flute and walking around three or four times so the error got spammed a couple of times.
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/2704446/debug.log)

**Comment by mlangsdorf** [comment]
No, that's fine.  I thought I had caught all of these.
