### ISSUE TITLE
Tiles display issues

### ISSUE THREAD

**Issue by OzoneH3** [CleverRaven/Cataclysm-DDA#28398]
Moved to its own issue from #28380

**EDIT: With the recent changes in #28403 these problems are now gated behind
the scaling factor bigger than x1.**

Linux:
Resets scaling factor back to 1x and terminal to 80x24 on game restart.

Windows:
Does a short full-screen flicker when opening without it being set to full-screen.
Remembers the terminal size and scaling option but displays like posted in Ticket #28350.
Manually dragging the window bigger/closer shows the correct scaling.

![](https://user-images.githubusercontent.com/3514404/53350427-57201300-391f-11e9-9a39-92ca8e983088.gif)

**Comment by ifreund** [comment]
Alright I can reproduce the Linux issue on a Lubuntu vm, will get to work on a fix.

**Comment by Treah** [comment]
Something similar occurs with non tiles build where the console version does not scale to the window and then crashes on the menu.

**Comment by Treah** [comment]
NOTE: With the non tiles build issue if you load a game it works ok its only this main title window thats borked.

**Comment by ifreund** [comment]
The terminal builds are fixed by #28380 as far as I can tell.

**Comment by Zireael07** [comment]
Scaling resetting back to 1x on Linux and terminal size going back to 80x24 is still an issue, as I just discovered on my new rig. Bump.

**Comment by ifreund** [comment]
Yeah, scaling factor of more than 1x doesn’t work in windowed mode on Linux because of what is presumably a bug in SDL. (The same code works fine on macOS and windows and SDL *should* be cross platform.) 

It should still work fine in full screen and borderless window mode on linux.

I haven’t been able to figure out a workaround for all window managers yet.  I could disable the screen size check for windowed mode on Linux, but that has potential to cause the game to crash on load depending on the settings and the window manager of the users system.

**Comment by Fixer-007** [comment]
Seen blinking in main menu when viewing MOTD (as example), Win7, intelHD. No problems ingame or in tiles.

**Comment by ZhilkinSerg** [comment]
I think it is resolved now.

**Comment by Night-Pryanik** [comment]
Closing until reconfirmed.
