### ISSUE TITLE
Homebrew fails to install Cataclysm

### ISSUE THREAD

**Issue by JosephCarrington** [CleverRaven/Cataclysm-DDA#28861]
**Describe the bug**  
Using `homebrew reinstall catataclysm --HEAD` fails with `Errno::ENOENT: No such file or directory - lua`

Specifically:
```
jcarrington$ brew reinstall cataclysm --HEAD
==> Reinstalling cataclysm 
==> Cloning https://github.com/CleverRaven/Cataclysm-DDA.git
Updating /Users/jcarrington/Library/Caches/Homebrew/cataclysm--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 060ba58634 Merge pull request #28852 from cburns2017/mac_compiling_correction
==> make NATIVE=osx RELEASE=1 OSX_MIN=10.13 LUA=1 USE_HOME_DIR=1 TILES=1 SOUND=1 CLANG=1
Error: An exception occured within a child process:
  Errno::ENOENT: No such file or directory - lua
```

**To Reproduce**  
use Homebrew to reinstall cataclysm

**Comment by ifreund** [comment]
Looks like the brew formula needs to be updated after removing lua.  I'll try and send a pr over there

**Comment by ifreund** [comment]
https://github.com/Homebrew/homebrew-core/pull/38112

**Comment by ifreund** [comment]
Should be fixed.

**Comment by keupo** [comment]
This is still a problem for me.

Red: brew reinstall cataclysm
==> Reinstalling cataclysm
==> Cloning https://github.com/CleverRaven/Cataclysm-DDA.git
Updating /Users/parkerkraus/Library/Caches/Homebrew/cataclysm--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at ea190d32b1 Update Brightnights item groups folder to item_groups
==> make NATIVE=osx RELEASE=1 OSX_MIN=10.14 LUA=1 USE_HOME_DIR=1 TILES=1 SOUND=1 CLANG=1
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - lua

**Comment by JosephCarrington** [comment]
You’ll have to uninstall then install it it. The reinstall appears to use the same formula
