### ISSUE TITLE
Misaligned projectile paths in Tiles release w/ Tilesets disabled

### ISSUE THREAD

**Issue by Taberone** [CleverRaven/Cataclysm-DDA#29627]
**Describe the bug**  
Projectile paths are misaligned when using Tiles version of CDDA AND Tilesets are disabled.

**To Reproduce**  
1. Get something you can throw or shoot. Make sure to use "Tiles" release and disable tilesets.
2. Throw or shoot it.
3. Notice that the red asterisks (indicating the path of a projectile) are horribly misaligned and show up nowhere near where you were aiming.

**Expected behavior**  
Red asterisks that demonstrate projectile path are aligned properly between the player and the target being aimed at.

**Screenshots**  
![2019-04-15 17_53_55-Cataclysm_ Dark Days Ahead - 0 D-1804-g2eb2f63](https://user-images.githubusercontent.com/9733597/56174794-223c4e00-5fa9-11e9-93dd-2fc63850f6c6.png)

See the red asterisks? That's the projectile flight path.

**Versions and configuration(please complete the following information):**
 - OS: Win7
 - Game Version: 0.D-1804-g2eb2f63
 - Graphics version: Tiles (But tilesets disabled)
 - Mods loaded: None. Tested on a fresh new world with only Dark Days Ahead loaded, still happens.

**Additional context**  
None.

**Comment by Digi1980s** [comment]
It has been fixed in the past few experimental builds, I believe.

**Comment by reed501** [comment]
I tried to fix this and it was merged yesterday. I'm now running your exact version and am unable to replicate this. Are you sure the version is correct? Or maybe you're just a bad shot?
Is it possible the asterisks are something else? Maybe something else shooting, like a turret?

In any case, if it's still happening and it's legit then send some more info so I can try and see why I can't reproduce the issue.

**Comment by Taberone** [comment]
Still happening, even on another fresh save file (Only Dark Days Ahead loaded). Not sure what other info I could send.

Nobody else is shooting. The asterisks only appear when throwing/shooting, and they're still misaligned. 
Even if I was a bad shot, there's no way the asterisks would be THIS misaligned to appear all the way in the middle of nowhere, rather than being traced from my character's location.

Version is correct, because I got it right from the main menu.

Minimap and sidebar are on. Could this be the way I install/update my CDDA installation? I don't bother with the launcher because it's too problematic and broken for me. I just download the Releases and drop them into a special folder for CDDA, overwriting everything.

**Comment by Zireael07** [comment]
What settings did you use with the older install? Maybe there was something that was conflicting in your settings...?

**Comment by Taberone** [comment]
Probably, but the older install is long gone now in the recycle bin.

**Comment by Night-Pryanik** [comment]
#29657 should've probably resolved this. Anyway, closing until reconfirmed.
