### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by hitmancho** [CleverRaven/Cataclysm-DDA#29800]
After updating to build 8823 from remroy's launcher and manually updating Arcana and dissociativity's PK rebalancing as I have done for the past months, the game won't start today, with the follwing log:

CRASH LOG FILE: config/crash.log
VERSION: 0.D-2076-gc71b04b
TYPE: 9JsonError
MESSAGE: line 1:1: tried to start object, but found '
STACK TRACE:
    @0x5603C5[cataclysm-tiles.exe+0x1603C5]
    @0x560F72[cataclysm-tiles.exe+0x160F72]
    IMG_LoadWEBP_RW+0x194248@0x10C8C78[cataclysm-tiles.exe+0xCC8C78]
    IMG_LoadWEBP_RW+0x4C31C3@0x13F7BF3[cataclysm-tiles.exe+0xFF7BF3]
    IMG_LoadWEBP_RW+0x4C8CAE@0x13FD6DE[cataclysm-tiles.exe+0xFFD6DE]
    @0x81B0ED[cataclysm-tiles.exe+0x41B0ED]
    @0x81E6F0[cataclysm-tiles.exe+0x41E6F0]
    @0x820200[cataclysm-tiles.exe+0x420200]
    @0x82073D[cataclysm-tiles.exe+0x42073D]
    @0xD86C35[cataclysm-tiles.exe+0x986C35]
    @0xD8B838[cataclysm-tiles.exe+0x98B838]
    @0x83EE11[cataclysm-tiles.exe+0x43EE11]
    IMG_LoadWEBP_RW+0x4F8C40@0x142D670[cataclysm-tiles.exe+0x102D670]
    @0x4013ED[cataclysm-tiles.exe+0x13ED]
    @0x4014FB[cataclysm-tiles.exe+0x14FB]
    BaseThreadInitThunk+0xD@0x76D7555D[kernel32.dll+0x1555D]
    RtlUserThreadStart+0x1D@0x76ED385D[ntdll.dll+0x5385D]

**Comment by codemime** [comment]
Most likely related to a mod. Please don't neglect the template when submitting an issue.

**Comment by GenericDM** [comment]
Update to build 8824, that should fix it.

**Comment by hitmancho** [comment]
The error still persists, attaching my log.
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3104477/crash.log)

The mods I am using:
[
  "dda",
  "no_npc_food",
  "aftershock",
  "Tolerate_This",
  "SD_Magcrafting",
  "realguns",
  "SD_Magcrafting_Realguns_Extension",
  "craftgp",
  "FIC_Weapons",
  "growable-pots",
  "ew_pack",
  "makeshift",
  "Medieval_Stuff",
  "More_Survival_Tools",
  "nw_pack",
  "modular_turrets",
  "PK_REBALANCE",
  "Salvaged_Robots",
  "alt_map_key",
  "Mining_Mod",
  "mutant_npcs",
  "MMA",
  "zets_hair_extensions",
  "more_locations",
  "zets_hair_ext_more_locations",
  "zets_hair_ext_pk_rebalance",
  "mapgen_demo",
  "cityside",
  "boats",
  "deoxymod",
  "blazemod",
  "Tanks",
  "Arcana",
  "DP_XOTTO_INDICATORS",
  "winning_dda",
  "more_classes_scenarios",
  "no_reviving_zombies",
  "speedydex",
  "StatsThroughSkills"
]

**Comment by hitmancho** [comment]
Failed to clarify: the game itself won't start, not even a main menu. Not talking about loading a save file.

**Comment by Zireael07** [comment]
With such a large list of mods, your only option is probably to start removing them one by one to see which one causes the problem.

**Comment by ZhilkinSerg** [comment]
If game doesn't start, delete `config` folder and try starting game again. If it doesn't help - try reinstalling the game. Report if it still doesn't start.
