### ISSUE TITLE
Crafting with water from shallow pool results in insane amount of byproduct water 

### ISSUE THREAD

**Issue by Yunatan** [CleverRaven/Cataclysm-DDA#29835]
**Steps to reproduce the behavior**  
1. Try to make some pine needle tea standing near the shallow water tile and using water from it
2. After the crafting is finished be asked "What to do with water?"
3. Pour water on the nearby empty ground tile 
4. Check the water on the ground
5. Be astounded by the amount of it 
6. Try to move around 
7. Experience have lagging 

**Expected behavior**  
There shouldn't be any byproduct water from making tea in the first place. 

**Screenshots**  
![image](https://user-images.githubusercontent.com/6611291/56533319-1c71da00-6560-11e9-896f-086cbb0381fc.png)
![image](https://user-images.githubusercontent.com/6611291/56533342-2398e800-6560-11e9-9542-3457259bb332.png)
![image](https://user-images.githubusercontent.com/6611291/56533388-34495e00-6560-11e9-9cf1-e2559766cccf.png)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D-2035-g3fae041 (tiles)

**Comment by anothersimulacrum** [comment]
Already fixed in #29823

**Comment by Yunatan** [comment]
Hm, I have updated the game but the bug still reproduces. Is it because of my save files? Do I have to start a new run after the update?

**Comment by Yunatan** [comment]
Oops, never mind, it is just not deployed yet

**Comment by anothersimulacrum** [comment]
What version did you update to when you updated? Was it 0.D-2107-f1de98d (or something like), or was it something else?
The Jenkins server is privately maintained I believe, but you can donate to the [patreon for C:DDA](https://www.patreon.com/user/overview?u=15922455).

**Comment by Yunatan** [comment]
> What version/build did you update to when you updated? Was it 0.D-2107-f1de98d (or something like), or was it something else?

0.D-2092-gdf6c61e (tiles)

**Comment by anothersimulacrum** [comment]
This issue should be fixed when you update again then. 
Please close the issue if you cannot reproduce it when you update.

**Comment by Yunatan** [comment]
Yep, the build just finished, I've updated (0.D-2107-gf1de98d (tiles)) and the issue is resolved. Partially. I still don't understand why am I handed a unit (1) of water when I fail to make a tea. Can't it just go back into the shallow water pool automatically? Is it intended behavior?

**Comment by anothersimulacrum** [comment]
You should report that in a separate issue, but it should go back in the water automatically.

**Comment by Yunatan** [comment]
No problem, thank you!
