### ISSUE TITLE
Dog is  Crashing the game

### ISSUE THREAD

**Issue by SirClarke** [CleverRaven/Cataclysm-DDA#30440]
Every time I try to feed a dog it crashes the game
Just feed the Dog (Dog food) 

**Expected behavior**  
I expect the dog to be my pet?

**Screenshots**  
![Screenshot (60)](https://user-images.githubusercontent.com/31796878/57579203-e345cf00-7466-11e9-85ad-6f81aced6051.png)

**Versions and configuration(please complete the following information):**
 - OS:windows 10
 - Game Version: 0.D-2832-g38838dc (tiles)
 - Graphics version: Tiles
 - Mods loaded: 
![image](https://user-images.githubusercontent.com/31796878/57579228-3fa8ee80-7467-11e9-831e-c81b270798da.png)
![image](https://user-images.githubusercontent.com/31796878/57579239-551e1880-7467-11e9-9b41-6ae3e13572f7.png)
![image](https://user-images.githubusercontent.com/31796878/57579248-66ffbb80-7467-11e9-96b3-59e7b2d85405.png)

**Comment by dom4op** [comment]
Somehow I doubt it's the dog that causing the crash. After updating to 8947 my game crashes no matter what I do. Just taking a step crashes the game.

https://i.imgur.com/HaxOqhX.jpg

It was fine on 8941, so I'll just revert to that build. 
No mods.

**Comment by SirClarke** [comment]
Hmm odd I've had no other problems so far "Knock on wood" but maybe your right could just be something odd with the update

**Comment by ZhilkinSerg** [comment]
Can you provide a savegame prior to crash?

**Comment by gr0mazeka** [comment]
Somehow I doubt it's the dog that's causing the crash. After updating to 8947 my game crashes no matter what I do. Just taking a step crashes the game.
https://imgur.com/a/5QhgmTU
It was fine on 8942, so I'll just revert to that build.

**Comment by dom4op** [comment]
Here is the save:
[Highgate.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3169898/Highgate.zip)
Just make a step in any direction and the game will crash.
There is a single personal mini-mod tweaking some .json values regarding spawn rate of certain locations, the save should work without the mod. But just in case:
[Grimwulf_mod.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3169899/Grimwulf_mod.zip)

**Comment by neitsa** [comment]
I'm not sure this is the same cash as OP, but I can definitely repro the crash with your save file @dom4op .
We should split this crash onto another post I think, until we are sure they are the same.

```
>	Cataclysm-App-Debug-x64.exe!monster::attitude(const Character * u) Line 923	C++
 	Cataclysm-App-Debug-x64.exe!monster::plan(const std::map<int_id<monfaction>,std::set<monster *,std::less<monster *>,std::allocator<monster *> >,std::less<int_id<monfaction> >,std::allocator<std::pair<int_id<monfaction> const ,std::set<monster *,std::less<monster *>,std::allocator<monster *> > > > > & factions) Line 230	C++
 	Cataclysm-App-Debug-x64.exe!game::monmove() Line 4171	C++
 	Cataclysm-App-Debug-x64.exe!game::do_turn() Line 1484	C++
 	Cataclysm-App-Debug-x64.exe!SDL_main(int argc, char * * argv) Line 689	C++
 	Cataclysm-App-Debug-x64.exe!main_getcmdline(...) Line 177	C
 	[External Code]	
```
https://github.com/CleverRaven/Cataclysm-DDA/blob/56c8b8cd84c49c37e1327c483bb65c0c5019e2ee/src/monster.cpp#L923-L925

```
        if( np->is_hallucination() ) { // np = nullptr.
            return MATT_IGNORE;
        }
```

called from:

https://github.com/CleverRaven/Cataclysm-DDA/blob/56c8b8cd84c49c37e1327c483bb65c0c5019e2ee/src/monmove.cpp#L230

The function default to passing a nullptr:

```
        monster_attitude attitude( const Character *u = nullptr ) const;
```

**Comment by neitsa** [comment]
@dom4op : fixed in #30445

**Comment by dom4op** [comment]
Thank you!

**Comment by SirClarke** [comment]
Nope sadly not fixed thanks anyways 
![Screenshot (61)](https://user-images.githubusercontent.com/31796878/57582044-0afc5d80-748e-11e9-934a-0227556493b5.png)

**Comment by ZhilkinSerg** [comment]
There were no release with that PR yet.

**Comment by SirClarke** [comment]
Not sure what you mean by that I'm not very computer illiterate sadly...

**Comment by gr0mazeka** [comment]
Thank. Good job.

**Comment by ifreund** [comment]
Closing as this has been fixed in #30445

**Comment by SirClarke** [comment]
Thanks a ton
