### ISSUE TITLE
Butchering continues automatically (in potentially dangerous situations)

### ISSUE THREAD

**Issue by BaumgeistOne** [CleverRaven/Cataclysm-DDA#33250]
# Describe the bug

I was dissecting two bio-operators, when another bio-operator nearby came back from the dead. I was prompted if I would like to continue* butchering, I said no and was able to act. Then I took off my duffel bag, and after that action the butchering automatically continued until I was attacked, when I was prompted again if I would like to continue* butchering. After the fight I tried to dig up the pile of metal the new bio-operator had fallen under, and again the old butchering command continued, without the pile of metal getting cleared. After the butchering finished, I was finally able to clear the pile of metal.

*I'm not sure anymore if the prompt asks whether to "stop" or "continue". I hope it does not matter.

# Steps To Reproduce

1. Kill some zombies, put them on the same tile
2. Use the "butcher all" command
3. Get interrupted by anything, choose to stop butchering
4. Notice that after certain actions the butchering continues automatically

# Expected behavior

I would expect the butchering to only continue if I choose to.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on Windows 7
- Game Version: 0.D-6539-g39eb17e [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Mythical Martial Arts [MMA],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    sees-player icon, +attitude [sees_player],
    StatsThroughSkills [StatsThroughSkills]
]

# Additional context

I think I have encountered this problem before, but I have no idea how long ago that was.

**Comment by Muffindrake** [comment]
This occurs a lot for me when I try to dissect corpses and new company wanders in (which is frustrating in itself). Only that it will continue to attempt dissecting after the threat is gone and I'm still in range of the corpse ... or worse, continue to 'dissect' a non-existant corpse to waste several hours without being able to cancel it.

**Comment by Svankensen** [comment]
I  experienced similar bugs. It continued dissection and moved the corpse from its original location to a seemingly random one nearby.

**Comment by Reaper9** [comment]
Have the same issue on 9479.

**Comment by Nerdy314159265** [comment]
This bug still exists in 9604. I will cancel a butchering because of an enemy showing up, then it will (seemingly) randomly start butchering while I fight or get away. This effect even carries across z-levels all until I'm back to my car, where it will eventually finish the butchering and pop zombie guts out of nowhere onto the ground.

**Comment by kevingranade** [comment]
So the butchering action definitely gets pushed onto the backlog when the interruption occurs, but after that there are two bugs happening.
One is, when a triggering action completes, it segues directly into the butcher action, which is not right. I *think* butchering needs the "no auto resume" flag, it should be resumed when the player is standing at the same location and enters the butchery menu again, not when some other activity completes.
I suspect it is configured this way in order to allow NPCs to, "start butchering", then move to the butcher location (pushing the butcher action onto the stack), then when the "move to location" action is completed, butchering starts.
Second, it looks like butchering doesn't check that it is still in range of the target corpses on resume, again this is possibly because it expects to navigate there first.

**Comment by davidpwbrown** [comment]
I think I've fixed this in the linked PR, but I cant reproduce on latest master to be 100% sure.
Do you have a reproducible save ?

**Comment by BenlyAZ** [comment]
This bug or one very much like it is still around in the latest experimental. I was only butchering one corpse at a time, as well.

**Comment by jarmush** [comment]
I reproduced this bug in latest cataclysmdda-0.D-Linux_x64-Tiles-9908.tar.gz
Problem isn't fixed

https://www.dropbox.com/s/j5z34reia7zulm8/%D0%A5%D0%BE%D1%81%D0%B5.tar.gz?dl=0
