### ISSUE TITLE
Vehicle disappear when moving from another mapchunk and re-appear when in vehicle mapchunk

### ISSUE THREAD

**Issue by drago888** [CleverRaven/Cataclysm-DDA#38292]
# Describe the bug

Vehicle disappear when entering a new mapchunk but reappear when moving back into vehicle mapchunk

A gigantic vehicle working as Power grid for my base will disappear when I exit the vehicle mapchunk that the vehicle is on. It will reappear with the vehicle parts in the other mapchunk when I enter the vehicle mapchunk.

Version: 0.D Stable

# Steps To Reproduce

1. Create a vehicle near the border of 2 mapchunks
2. Extend the vehicle such that it extends into the other mapchunk
3. Move towards the other mapchunk and observe if vehicle disappear
4. If disappear, walk towards the vehicle mapchunk to see it appearing

# Expected behavior

The vehicle shall exist in both mapchunk if there are any cross mapchunk.
Thus there shall not be disappearing cases.

# Screenshots

Still in mapchunk - 
![Uploading 20200224-screenshot.png…]

One step out of mapchunk -
![20200224-screenshot_1](https://user-images.githubusercontent.com/14855901/75132200-05b48a80-5711-11ea-9e6b-4f0a6888bca2.png)

# Versions and configuration

 - OS: [Ubuntu 18.04]
 - Game Version: [cataclysmdda-0.D-8574]
 - Graphics version: [Tiles]
 - Ingame language: [English]
 - Mods loaded: [dda, filthy clothing, bens GF Recipes,Craftable Gun pack, extended realistic guns, makeshift items mod, medieval and historic content, more survival tools, modular turrets, salvaged robots, alternative map keys, mutant npc, more location, fuji's more building, boats, vehicle additions packs, tanks and other vehicle ]

# Additional context

**Comment by drago888** [comment]
Screenshots

Still in mapchunk -

![20200224-screenshot](https://user-images.githubusercontent.com/14855901/75132889-a015cd80-5713-11ea-997f-609a4a9838d3.png)

**Comment by Funguss** [comment]
I do believe this has been fixed. I'll try loading your save up.

**Comment by drago888** [comment]
Hihi Funguss,

Will try downloading the experimental to test probably tomorrow.

Thanks. If still not fixed, will upload my save file.

**Comment by drago888** [comment]
Hi Funguss,

Tried with experimental 0.D-12517-g92b0b2c and problem still persist.

Attached is the save file. Even tried removing offending vehicle part and inserting but still same issue. 

Thanks
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4247873/save.zip)

**Comment by Funguss** [comment]
Ok, wow, yeah it looks like your vehicle is getting unloaded, though moving one square east doesn't take you into a new chunk. IIRC vehicles unload when their point of origin (the first tile constructed) leave the simulated area. I could have sworn this issue was fixed. I was also certain that jumper cables prevented vehicles unloading until their connected vehicles were unloaded, too. Sorry for getting your hopes up!

It may be that the vehicle is invisible, or that it's still loaded but isn't placed on the map. I'm not entirely sure how to go about testing this.

**Comment by Qrox** [comment]
Just a wild guess, but it could also be an issue with the submap vehicle cache.

**Comment by BevapDin** [comment]
This is a limitation of the game engine. Each vehicle is stored within a map chunk and if that map chunk is not part of the reality bubble, the vehicle it contains are not part of the reality bubble either.

Fixing this would need to load *all* (or at least very many) surrounding map chunks just to load the vehicles that are also part of the reality bubble. And vehicles have no size limit, so we would have to expect a vehicle stored a dozen map chunks away can still have parts in the reality bubble.

You can make multiple vehicles and connect them via jumper cables.
