### ISSUE TITLE
map::find_clear_path returns invalid trajectory for some 3D cases

### ISSUE THREAD

**Issue by olanti-p** [CleverRaven/Cataclysm-DDA#39693]
# Describe the bug
When 3D FOV enabled, `map::find_clear_path` returns weird values when `abs(dx) == dz` or `abs(dy) == dz`

# Steps To Reproduce
1. Move into a clear field
2. Run the improvised tests: [map_fcp_bug.cpp](https://github.com/CleverRaven/Cataclysm-DDA/files/4497038/map_fcp_bug.txt)
3. None of them fail, but 7 should

# Expected behavior
`map::find_clear_path` returns a valid trajectory

# Versions and configuration
- OS: Linux
    - OS Version: Description: Ubuntu 19.10; Release: 19.10; Codename: eoan; 
- Game Version: f94cfe10ed0752bc043d76bf77db56e95c00a628 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm]
]

# Additional context
I'm not familiar with CDDA's tests, but there doesn't seem to be any for `map::find_clear_path`.

**Comment by kevingranade** [comment]
Should be fixed by #38730

**Comment by olanti-p** [comment]
Nope, still happens on current master. You can see it while aiming: the code basically calls `g->m.find_clear_path(g->u.pos, dst)` (where `dst` is cursor position) and draws returned trajectory. Try aiming 10 tiles north, 2 tiles west and 2 tiles up - the trajectory shrinks to "2 tiles north, 2 tiles west, 2 tiles up"

Could be related to / a dupe of #13601 btw
