### ISSUE TITLE
Segfault crash during CBM installation

### ISSUE THREAD

**Issue by Bdole1454** [CleverRaven/Cataclysm-DDA#39738]
# Describe the bug

Segfault occurs during a long CBM installation in a multi-level lab. If i had to guess its due to a memory leak or overflow with a lot of stuff going on in the background, as experimental Z levels are turned on.

# Steps To Reproduce

1. Load up the attached save file, character is Cary Elliott
2. Attempt to install Cerebral Booster CBM

# Expected behavior

Installation without fault or crash

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-955-gced4d81 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Rail Stations [No_Rail_Stations],
    Alternative Map Key [alt_map_key],
    No Fungal Monsters [No_Fungi]
]

# Additional context

I have experienced this crash on this save file before, but this is the first persistent and repeatable instance of it

Attached zip file includes save, crash, and debug files

- 
[Uploading CDDA.zip…]()

**Comment by Bdole1454** [comment]
Not sure the zip uploaded so reuploading the files separately 
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4500732/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4500733/debug.log)
[Owls Head.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4500735/Owls.Head.zip)

**Comment by ScarPan** [comment]
Just had a similar crash after successfully installing Recycler Unit CBM at second floor of a Doctor's office. The log is attached.
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4500862/crash.log)

**Comment by ArtofWASD2** [comment]
Also have this crash. No Z Levels. It appears you can brute force through it by crashing multiple times until it works.

**Comment by Qrox** [comment]
@Fris0uman Probably cause by #39647. 62d849f0278137e4cac739bb8067290038b99068 changes the order of parameters in `str_value` but did not update `activity_handlers::operation_finish` accordingly.

**Comment by Bdole1454** [comment]
In the process of testing various CBMs, since i was previously able to install an ethanol burner and mk2 power CBMs. Wired reflexes also craches

**Comment by anothersimulacrum** [comment]
Fixed by #39715?

**Comment by Fris0uman** [comment]
Damn, sorry about that U_U". I'll fix it later today if no one does it before. (Not fixed by #39715 )
