### ISSUE TITLE
Items of type TOOL_ARMOR cannot be reloaded, regardless of correct pocket_data

### ISSUE THREAD

**Issue by Axema** [CleverRaven/Cataclysm-DDA#40765]
# Describe the bug

Most items of type `TOOL_ARMOR` generally require charges to function. The current format for updating tools is to additionally assign a pocket of type `MAGAZINE` to restore functionality. However, it appears that armor of all types, wearable tools included, parse any included pockets, even those of magazine type, as storage rather than interpreting it as where to hold charges. This is not presently visible as tool_armor.json has not yet been updated with pocket data for holding charges.

# Steps To Reproduce

1. Add the appropriate `pocket_data` to a `TOOL_ARMOR`, such as a gas mask.
2. Debug in a gas mask, noting that it will still spawn with zero charges when tools and magazines tend to spawn fully-loaded when debugged in.
3. Debug in gas mask filter ammunition.
4. Attempt to reload the gas mask. It will report that you have no available ammunition to reload it with and fail to reload, despite presence of the correct ammunition.

# Expected behavior

Reload correctly parses ammunition is available in present in inventory, allowing one to reload the item in question.
# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.E-2382-g48f8edf [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

The message printed by attempting to reload an item that requires `pocket_data` to be loadable is different, instead stating that that item cannot be reloaded.
It is additionally possible that https://github.com/CleverRaven/Cataclysm-DDA/pull/40399 might render this issue obsolete via making magazine-type pockets no longer mandatory for tools to reload properly, but this oversight might still be desirable to correct.

**Comment by KorGgenT** [comment]
this sounds a lot like it will be fixed in the linked PR.

**Comment by Axema** [comment]
This appears to have been fixed, though the conjecture in "additional context" proved to be incorrect. Tool armor will reload properly if given correct magazine-type pocket_data, with tool_armor.json merely needing to be updated.

However, a different problem has cropped up:

![Infinity](https://cdn.discordapp.com/attachments/709600070810730518/713722202301661184/unknown.png)

It seems that most use actions are no longer respecting actually being loaded. In this example, the RX12 jet injector has not yet been updated and thus can't even be loaded with ampoules at all, but can instead be freely used as often as one desires, due to it no longer respecting `charges_per_use`.

**Comment by kevingranade** [comment]
Fixed, probably by #40399

**Comment by ektoplazm** [comment]
This problem still persists, gas masks cannot be reloaded, they don't even appear in the "r" menu: 
![image](https://user-images.githubusercontent.com/60448096/82905576-b62e6680-9f6c-11ea-8efd-67432368f747.png)
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-2476-g1b2af09 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]
