### ISSUE TITLE
What to do with nonexistent liquid dialog stuck

### ISSUE THREAD

**Issue by REDJAY12** [CleverRaven/Cataclysm-DDA#40786]
# Describe the bug
Just updated to most recent experimental. After randomizing a new character, talking to an NPC, and trying to move around (2x), a dialog concerning loose red sauce shows up and cannot be closed. My character does not have red sauce in their inventory. I had just interacted with a nearby NPC and asked them for an item, but was told "they have nothing to give".

**EDIT: Character was saved after interacting with NPC. I copied the character to template, loaded the template as a new character on the same world and immediately had the same issue, but this time the liquid changed to barley wine (1).

**EDIT 2: Further new characters using this template are not having the issue. I tried copying the world settings to a new world and could not reproduce the issue even with the exact same sequence of events.

***EDIT 3: Happened randomly on another character, walking along a road toward a group of NPC Thugs. It was pretty much the instant they came into my bubble. I had been walking along for a few minutes before this without any issues and never touched/picked up any items and had no companions.

# Steps To Reproduce
Not sure this can be easily reproduced. Might have just been bad luck with the NPC.
1. Make a random player character.
2. Talk to NPC and request an item. They claim not to have any.
3. Recruit NPC.
4. Try to walk 2 steps in any direction.
5. What to do with red sauce (fresh) (8)? This dialog cannot be closed.

# Expected behavior
I expected not to get lost in the sauce.

# Screenshots

Inventory immediately before trying to walk away:

![image](https://user-images.githubusercontent.com/65835998/82742964-72e8b380-9d32-11ea-9ac0-64b63ed8e42b.png)

Bug:

![image](https://user-images.githubusercontent.com/65835998/82743046-5e58eb00-9d33-11ea-89e5-68b0fe38c276.png)

# Versions and configuration

- OS: Windows 8.1
- Game Version: 0.E-2411-g7fcce2c [64-bit]

**Comment by hexagonrecursion** [comment]
I experienced this too. In my case no NPC interaction was involved and it was possible to close the dialogue by pouring the liquid on the ground.

Steps To Reproduce (very unreliable)
1. Play now (fixed scenario)
2. Take one step
3. See the dialogue

- OS: Linux
    - OS Version: Fedora release 32 (Thirty Two)
- Game Version: 0.E-2411-g7fcce2c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by anothersimulacrum** [comment]
Fixed by #40975?

**Comment by hexagonrecursion** [comment]
I can still reproduce this.
```
- OS: Linux
    - OS Version: Distributor ID: Fedora; Description: Fedora release 32 (Thirty Two); Release: 32; Codename: ThirtyTwo; 
- Game Version: 0.E-2899-g0ff7d77 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]
```

Also: I get asked what to do with random liquids several times when I approached a refugee center. Could this be related to NPC?

**Comment by anothersimulacrum** [comment]
So, what you're getting is that the pour into container option doesn't work? You mentioned  earlier that the pour onto ground one does.

**Comment by hexagonrecursion** [comment]
- Pouring on the ground works
- Pouring into container also works (if you have an empty container)

The bug is that random liquids appear out of nowhere.

**Comment by anothersimulacrum** [comment]
Then this was fixed by #40975.
That's a separate issue - #40127 - cans are spawning opened, and when they spawn in NPC inventories, the character is prompted about what to do with them, because NPCs can't make those decisions.
