### ISSUE TITLE
Freeze when loading a save

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#41648]
# Describe the bug

Made a save to demonstrate another issue, now game hangs while trying to load it.
*Correction* - game loads but it takes at least 15 minutes, compared to my usual 15-20 seconds. Something is definitely wrong here.
*Correction 2* - later saves freeze indefinitely.

# Steps To Reproduce

Try loading [the save](https://drive.google.com/file/d/1B47egdWkMH_ZWdLb2k5pXlZfEIAK5PCG/view?usp=sharing).

# Expected behavior

Game loading normally.

# Versions and configuration

 - OS: Windows 7
 - Game Version: 0.E-3553-ge888413
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: [dda, no npc needs, aftershock, magiclysm, alt map key, stats through skils]

Can't paste full debug message because to get it you need the game to actually load.

# Additional info
The only difference I can think of compared to previous saves is my char is holding orichalcum cauldron almost filled to the brim with other items. e: doesn't seems to be an issue - save without a cauldron hangs just like the one with it.

**Update**:  found something - debug.log follows
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4845192/debug.log)

I've snipped it but this error
`ERROR : src/item_contents.cpp:282 [void item_contents::combine(const item_contents&)] error: tried to put an item into a pocket that can't fit into it while loading.  err: only mods can go into mod pocket` spams for thousands of lines (and probably would've spammed for millions if I haven't killed game process; debug.log was at 17Mb after about a minute of freezing). Looks like game enters into an endless loop.

**Comment by GGgatherer** [comment]
So I left it working for several hours, and debug.log is as follows:
-regular debug messages (see linked debug.log in OP)
-backtrace (see linked debug.log in OP)
-98683 lines of `ERROR : src/item_contents.cpp:282 [void item_contents::combine(const item_contents&)] error: tried to put an item into a pocket that can't fit into it while loading.  err: only mods can go into mod pocket`
-98683 lines of `ERROR : src/item_contents.cpp:282 [void item_contents::combine(const item_contents&)] error: tried to put an item into a pocket that can't fit into it while loading.  err: item is too long`
After that nothing else is written to debug.log even if game process is left working for hours. It continues eating up about 1 processor core worth of CPU time.

**Comment by GGgatherer** [comment]
And for comparison, here's a [save](https://drive.google.com/file/d/1Cjuqz2zNcgFBZipvoKroxJQx64bLOBXI/view?usp=sharing) and [debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4852251/debug.log) of the game where it doesn't freeze but still have that error and multiple same lines in the log (but not nearly quite numerous, only 45 of each). Note that save in OP was made in the same world, just after exploring it a little compared to this one - I just went east and visited a couple of cities.

**Comment by olanti-p** [comment]
So, there is this `Ray Decker, Merchant` guy saved inside `o.-1.-1`
They have a duffel bag that contains 5 types of items: `saw`, `nailgun`, `heavy_flashlight`, `circsaw_off` and `rifle_22`.
There are 6561 copies of each item in the bag, 32805 in total. Uhm...

Removing the duffel bag severely shortens the debugmsg spam and makes the save loadable. Why they have so much stuff is beyond me - a bug in trader restock code?

[o.-1.-1 without the duffelbag](https://github.com/CleverRaven/Cataclysm-DDA/files/4860728/o.-1.-1.zip)

**Comment by anothersimulacrum** [comment]
I've run into at least one other person who had an NPC with an ungodly amount of items stored in some container

**Comment by misterprimus** [comment]
I get this with a battery being cloned in my inventory each time I load a 2-minute old save of a helicopter crash.

**Comment by hexagonrecursion** [comment]
This seems to be the same as https://github.com/CleverRaven/Cataclysm-DDA/issues/41776 which was fixed a while ago

**Comment by BrettDong** [comment]
>This seems to be the same as #41776 which was fixed a while ago

This issue is still there:
<img width="1072" alt="螢幕截圖 2021-01-13 下午9 23 28" src="https://user-images.githubusercontent.com/21075502/104536179-94f6b500-55e5-11eb-9598-f32f7edaebc9.png">

**Comment by hexagonrecursion** [comment]
@BrettDong please clarify. The error message you posted is expected to occasionally show up and is not itself a cause for concern. For example: you might see this error if you save the game in a version where an apple is 0.5L and load it in a version where an apple is 0.6L. Such situations are inevitable when items and containers get rebalanced.
* Are you experiencing item duplication?
* Does your save file take much longer to load than usual? If so, can you post your save file, please?

**Comment by kevingranade** [comment]
Not the same issue, but when I made the contained item to big for its container, it vanished instead of dropping on the ground.

**Comment by misterprimus** [comment]
> Not the same issue, but when I made the contained item to big for its container, it vanished instead of dropping on the ground.

I recall this having happened to me a while back. I believe it was a soldering iron with a battery compartment mod for car batteries. After an update I loaded a game, got the error, and the thing was nowhere to be found.

**Comment by hexagonrecursion** [comment]
How this is supposed to work:
1. Volume is rebalanced (again)
2. Items no longer fit their containers
3. You see the error message
3. The items vanish *for 1 turn*
4. After 1 turn the items can be found lying on the ground at our feet.

If this is not what you experience, could you please post a save file that triggers the error when you load it?

**Comment by misterprimus** [comment]
> How this is supposed to work:
> 
> 1. Volume is rebalanced (again)
> 2. Items no longer fit their containers
> 3. You see the error message
> 4. The items vanish _for 1 turn_
> 5. After 1 turn the items can be found lying on the ground at our feet.
> 
> If this is not what you experience, could you please post a save file that triggers the error when you load it?

That was over a month ago and unfortunately I no longer have the save.

**Comment by actual-nh** [comment]
This is in as a 0.F blocker "in progress". What's happening with it?

**Comment by anothersimulacrum** [comment]
When I load misterprimus's save I get an error about the m9 and radio not fitting in my inventory, and both drop to the ground (and do not remain in my inventory).

While the debugmsg probably isn't ideal, I can't reproduce a freeze or duplication anymore, so I'd suggest unless there is more information this is largely fixed, and we do need to communicate that an item has been dropped because it didn't fit.

**Comment by misterprimus** [comment]
> When I load misterprimus's save I get an error about the m9 and radio not fitting in my inventory, and both drop to the ground (and do not remain in my inventory).
> 
> While the debugmsg probably isn't ideal, I can't reproduce a freeze or duplication anymore, so I'd suggest unless there is more information this is largely fixed, and we do need to communicate that an item has been dropped because it didn't fit.

I, too, have encountered the error more recently and in the most recent scenario, it did appear on the ground the next turn, so I suspect the matter is solved unless someone can reproduce it.

**Comment by actual-nh** [comment]
@ZhilkinSerg, @anothersimulacrum, or whoever has the permissions: Could a `0.G` milestone be created and this moved to that?

**Comment by Night-Pryanik** [comment]
If it's not resolved entirely per se,  I guess it could be safely moved to Delayed blockers (for 0.G)

**Comment by PatrikLundell** [comment]
The 0.F milestone indication should probably be removed (in line with the other Delayed blockers (for 0.G) in 0.F Release Planning).
