### ISSUE TITLE
Isn't shown the nutritional value of several teas

### ISSUE THREAD

**Issue by Duck13Tales** [CleverRaven/Cataclysm-DDA#41736]
There are several "teas" that doesn't show their nutritional value, like the dandelion tea, while others are shown, like the pine needle tea.

# Steps To Reproduce

You only need to craft or see the recipe for them, you can use the "dandelion tea" as an example.

# Expected behavior

Most probably the correct would be to show the nutritional value for all the teas, or then don't show for any.

# Screenshots

![cataclysm tea](https://user-images.githubusercontent.com/67176313/86294888-ce2c8200-bbcb-11ea-9127-68b2ddac3067.png)

# Versions and configuration

I am using using the CDDA 0.E-b10798 with the mods:

DDA
Disable NPC needs
Stats through skills
Stats through kills
SpeedyDex

**Comment by anothersimulacrum** [comment]
I don't understand what the issue is? They both show nutritional information.

**Comment by Duck13Tales** [comment]
It is the vitamins(RDA). Dandelions for example are rich in vitamin A, C and has a bit of iron and calcium and most recipes preserve that, as most recipes overall preserve the nutritional value of their components, but then the dandelion tea lose all the dandelion vitamins?

It seems a bit inconsistent with the cooking system.

**Comment by Duck13Tales** [comment]
But if this is really this way ok!

**Comment by Duck13Tales** [comment]
Sorry, I just saw in the json that they have the flag NUTRIENT_OVERRIDE. I still am not used to looking up the json files.

The only way to change it then is editing those myself right? But then every time that I update the experimental I will need to edit again right?

Is there any way to change the way that the game deals with this flag? Maybe a config file?

**Comment by anothersimulacrum** [comment]
You can make a PR that removes that flag, then this is fixed for everyone. The [new contributor's guide](https://github.com/CleverRaven/Cataclysm-DDA/wiki/Guide-to-adding-new-content-to-CDDA-for-first-time-contributors) details how to do so.

**Comment by Duck13Tales** [comment]
Hya!

I did the changes but when I was about to up the PR I tested and noticed that though the recipes stated the nutrients correctly, the crafted tea didn't.

Any idea on what I am doing wrong? Or should I put the PR like this and ask there?

**Comment by Duck13Tales** [comment]
Hi!

I edited the json and the recipes are listing the nutrients correctly but the final product don't. I did the PR and asked what I needed to do but it was merged and I still don't know haha

So do you know what else do I need to change?

**Comment by Duck13Tales** [comment]
It seems that those weren't completely json"ized". The description of "wild_herbs" in the spice.json states that it has 9 calories and no vitamins but in game it says that it has 6 calories and some vitamins.

Is there a way for me to fix that?

**Comment by anothersimulacrum** [comment]
Oh huh, that's weird. I have no clue what causes that.
