### ISSUE TITLE
 A messenger bag disappears when storing it in a backpack

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#41802]
# Describe the bug

A messenger bag disappears under very specific circumstances. This bug appears to be 100% reproducible

# Steps To Reproduce

1. Start a new game with the "naked and afraid" "profession"
2. Wish for a messenger bag and drop it
6. Wish for a backpack (id: backpack) and wear it
7. Wield the messenger bag
8. Wield the messenger bag again to stop wielding it
9. See the "Stop wielding messenger bag" prompt
10. Choose "store in inventory"
11. The messenger bag mysteriously vanishes.

# Expected behavior

The messenger bag should be stored in the backpack

# Screenshots

none

# Versions and configuration

```
- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 32 (Thirty Two); Release: 32; Codename: ThirtyTwo; 
- Game Version: 0.E-3697-g9582e33 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]
```

# Additional context

- The contents of the messenger bag are also lost
- Putting the messenger bag into the backpack by examining the backpack and using [i]nsert works as intended. I was only able to trigger this bug by using the wield command.
- Using a dive bag instead of a messenger bag prevents the bug from triggering
- Using a second backpack (id: backpack) instead of a messenger bag triggers the bug
- This is different form #41536.  #41536 was triggered by [i]nserting rather than [w]ielding

**Comment by reed501** [comment]
Had a very similar situation but I didn't even have a backpack. Completely naked aside from holding a cardboard box with a few items in it. When I went to wield a branch, it asked me to store the cardboard box in my inventory (what inventory?) then it was gone.

**Comment by mqrause** [comment]
This should have been fixed with #42077.

**Comment by hexagonrecursion** [comment]
@anothersimulacrum This was closed by mistake. I can still reproduce this bug.
```
- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 32 (Thirty Two); Release: 32; Codename: ThirtyTwo; 
- Game Version: 0.E-4112-g5837d3f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]
```

**Comment by anothersimulacrum** [comment]
Sorry about that.
