### ISSUE TITLE
When scaling factor is set, language changes will not be applied

### ISSUE THREAD

**Issue by GeekDuanLian** [CleverRaven/Cataclysm-DDA#48255]
# Describe the bug
When scaling factor is set, language changes will not be applied.

# Steps To Reproduce
1. Set language to any other than English.
2. Set scaling factor to any other than 1x.
3. Save and restart the game.
4. Language is still English.

# Expected behavior
Scaling factor does not affect language settings.

# Versions and configuration
- OS: Windows 10 10586.1540
- Game Version: Latest experimental version: 11548 x64
- Graphics version: Tiles
- Ingame language: Any except English
- Mods loaded: Built-in mods, I think it is irrelevant

**Comment by BrettDong** [comment]
Cannot reproduce on macOS, self-compiled from 65515b1185a4c75aa617adc88ef84705834175a7. Probably a Windows OS specific issue, or related to the recent SDL library version bump on Jenkins build server.
<img width="1440" alt="螢幕截圖 2021-03-28 下午4 27 59" src="https://user-images.githubusercontent.com/21075502/112767055-916aab80-8fe2-11eb-9aa6-f9997d74ac70.png">

**Comment by BrettDong** [comment]
Translations also function normally with scaling on MSVC compiled version:
![image](https://user-images.githubusercontent.com/21075502/112767722-579ba400-8fe6-11eb-9b7c-077131bd2383.png)

**Comment by ZhilkinSerg** [comment]
Please send your configuration file (config\options.json).

**Comment by BrettDong** [comment]
Confirmed on Jenkins build 11545, but the problem does not appear on Jenkins build 11535.

**Comment by ZhilkinSerg** [comment]
Something in https://github.com/CleverRaven/Cataclysm-DDA/pull/48176, though I have hard time connecting these changes to scaling factor?

**Comment by BrettDong** [comment]
I don't think it's related to changes in source code, because the MSVC compiled version does not have the problem.

**Comment by ZhilkinSerg** [comment]
Must be a coincidence then with `mxe` version upgrade (which happened between builds 11538 and 11539).

**Comment by ZhilkinSerg** [comment]
> MSVC compiled version does not have the problem.

I can actually reproduce it on MSVC (with or without reverting #48176).

**Comment by BrettDong** [comment]
> I can actually reproduce it on MSVC (with or without reverting #48176).

What steps worked for you to repro this bug?

**Comment by ZhilkinSerg** [comment]
Change language to non-English.
Set scale to 2x and restart app - language is not changed.
Set scale to 1x and restart app - language changes.

**Comment by ZhilkinSerg** [comment]
Issue is reproducible in `0.E-3`, so I am ruling out any code changes in CDDA. Must be issue with SDL2.

**Comment by ZhilkinSerg** [comment]
I wonder if these changes in SDL 2.0.14 are related:

https://github.com/libsdl-org/SDL/blob/9de7eaf9ac2b8de76cf095fb51e7e4208180720a/WhatsNew.txt#L41-L42

**Comment by GeekDuanLian** [comment]
> Please send your configuration file (config\options.json).

For comparison test, all settings are default.

**Comment by ZhilkinSerg** [comment]
Can you please test if you have same issue on build 11550?

**Comment by GeekDuanLian** [comment]
> Can you please test if you have same issue on build 11550?

I just tested it and the problem remains.

**Comment by ZhilkinSerg** [comment]
> > Can you please test if you have same issue on build 11550?
> 
> I just tested it and the problem remains.

Thanks. Please try again with 11551 when it will be out today.

**Comment by GeekDuanLian** [comment]
11551 does not seem to have the 64-bit version I used before, so I will test the 32-bit version first.
And it is fixed! Now the language is switched normally.

**Comment by happyman1997** [comment]
I still have this problem
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/6227586/debug.log)

**Comment by GeekDuanLian** [comment]
I just tested 11552, and the 64-bit version is no problem.

**Comment by GeekDuanLian** [comment]
In the current latest version, this problem reappears.
