### ISSUE TITLE
Fleeing NPCs seem unable to use Ramps

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#49506]
# Describe the bug
While attempting to reproduce an Innocent killed bug and make sure that the guilt effect was firing I murdered many NPCs friendly and not.  I noticed that if I was standing near a bridge the NPC would flee until they hit the ramp and then run along the ramp until they jumped off the bridge into the water rather than going up the ramp.

# Steps To Reproduce
Go near bridge ramp
Debug in NPC
Scare them into fleeing
Watch them unable to interact with the ramp to continue fleeing.

# Expected behavior
The NPC to go up a z level and flee across the bridge.

# Screenshots

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: af4b28f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

**Comment by Founded1992** [comment]
I'm able to confirm this behavior for Windows Tiles x64 version 5861984. I also tested this behavior using the ramp in the Still Farm, and on top of the bridge. In both cases, NPCs were able to traverse the ramps while allied, but were unable to navigate through them when fleeing.

**Comment by actual-nh** [comment]
There was a performance issue with NPCs figuring out where to go to in order to get away from a bomb, solved by telling them not to go where there wasn't a floor - #47113.

**Comment by RenechCDDA** [comment]
Still an issue as of https://github.com/CleverRaven/Cataclysm-DDA/commit/c94dc0387513d5bba49eb7d74b2b51a7a4d8c4a0

Set them to fleeing with the debug menu, they ran up against the ramp and then shuffled back and forth along it until I got closer, at which point they decided to jump in the water instead.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/59ee820e-3d22-4cc3-857f-abe89746cfaf)
