### ISSUE TITLE
Manually inserting items into a container unreliably uses autopickup filter rules

### ISSUE THREAD

**Issue by BlackxSnow** [CleverRaven/Cataclysm-DDA#50292]
### Describe the bug

With a filter whitelist of 'M4A1' on a pocket, I was able to manually insert several magazines (including those unrelated to the M4A1) into the pocket, as expected. However when inserting ammunition the action returned https://github.com/CleverRaven/Cataclysm-DDA/blob/a3e48252cbc8b2e80e16537a68701f25b44dfc73/src/item.cpp#L9356.

After further minor testing it appears that inserting any raw ammunition or raw drugs (ie. not in a container) will throw based on the filter rules, however tools and magazines will not. Further item categories are untested.

### Steps To Reproduce

1. Set filter whitelist to an item not to be inserted.
2. Attempt to insert a magazine/tool/container, should succeed
3. Attempt to insert ammunition or drugs, should fail

### Expected behavior

Manual insertion should not respect filter rules, as the filter is 'auto pickup' and presumably if the user is manually inserting an item, they specifically want that item in there.

### Versions and configuration

- OS: Win 10 x64
- Game Version: bc28921
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: default + stats through [s]kills

**Comment by mqrause** [comment]
Is this 0.F? It's fixed in experimental versions with #49318. (And the fix is marked as a backport candidate.)

It happens for all stackable items, btw.

**Comment by VincentRoyceMorgan** [comment]
Not fixed for me, and I'm usually no more than a day  behind the latest experimental.
No matter what pocket autopickup settings you put in, they're ignored if you try to manually insert items into the container. Be it priority, item or category settings. Dropping items on the ground and picking them back up uses autopickup settings properly. Unloading magazines from weapons also works as it should.
In my case it's been me trying to put infrared goggles, gas mask, headlamp and earmuffs into a heavy survivor suit.

**Comment by BlackxSnow** [comment]
> Is this 0.F? It's fixed in experimental versions with #49318. (And the fix is marked as a backport candidate.)
> 
> It happens for all stackable items, btw.

Version is listed in the issue, I’m not familiar with the versioning system so I’m not sure what 0.F is. As far as I’m aware I’m playing the newest stable.

This certainly sounds like it’s been resolved by that fix. Sounds like Vincent may have misread the issue as what they describe is the expected behaviour

**Comment by anothersimulacrum** [comment]
You are playing version 0.F, the most recent stable.

**Comment by VincentRoyceMorgan** [comment]
> > Is this 0.F? It's fixed in experimental versions with #49318. (And the fix is marked as a backport candidate.)
> > It happens for all stackable items, btw.
> 
> Version is listed in the issue, I’m not familiar with the versioning system so I’m not sure what 0.F is. As far as I’m aware I’m playing the newest stable.
> 
> This certainly sounds like it’s been resolved by that fix. Sounds like Vincent may have misread the issue as what they describe is the expected behaviour

Perhaps I've gotten things mixed up. Though I've always had the impression that autopickup rules should apply even when manually inserting items. Or at the very least that's what would've been useful in my case.
I want those items to be specifically in that piece of clothing, in specific pockets. When they occasionally end up outside of them or somehow get mixed up, I thought that inserting them back manually should do as I've set in autopickup settings. Instead what happens is they go in while ignoring any and all rules I've set and that leads to a piece of clothing accepting only 3 out of the 4 items it should be able to hold and I then have to insert them in a specific order.
Apologies for any confusion I may have caused.

**Comment by BlackxSnow** [comment]
> > > Is this 0.F? It's fixed in experimental versions with #49318. (And the fix is marked as a backport candidate.)
> > > It happens for all stackable items, btw.
> > 
> > 
> > Version is listed in the issue, I’m not familiar with the versioning system so I’m not sure what 0.F is. As far as I’m aware I’m playing the newest stable.
> > This certainly sounds like it’s been resolved by that fix. Sounds like Vincent may have misread the issue as what they describe is the expected behaviour
> 
> Perhaps I've gotten things mixed up. Though I've always had the impression that autopickup rules should apply even when manually inserting items. Or at the very least that's what would've been useful in my case.
> I want those items to be specifically in that piece of clothing, in specific pockets. When they occasionally end up outside of them or somehow get mixed up, I thought that inserting them back manually should do as I've set in autopickup settings. Instead what happens is they go in while ignoring any and all rules I've set and that leads to a piece of clothing accepting only 3 out of the 4 items it should be able to hold and I then have to insert them in a specific order.
> Apologies for any confusion I may have caused.

It sounds like to me the solution to your issue is individually filling pockets when manually inserting, which I too would appreciate as a feature.
