### ISSUE TITLE
NATO rifle named "IF YOU SEE THIS IT IS A BUG"

### ISSUE THREAD

**Issue by DavisBroda** [CleverRaven/Cataclysm-DDA#50656]
### Describe the bug

The NATO 5.56 rifle (item id: nato_assault_rifle ) is now named "IF YOU SEE THIS IT IS A BUG". It appears to still function as a rifle, with the same stats as before, so it seems to just be a naming bug, rather than anything functional.

### Steps To Reproduce

look at the name of item with ID nato_assault_rifle

### Expected behavior

rifle should have a real name

### Screenshots

![gun_bug](https://user-images.githubusercontent.com/15205060/128936944-9ced23c0-fb7f-4238-8887-e9d5c31e2fb3.PNG)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: ed2f630 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    DinoMod [DinoMod],
    No Fungal Monsters [No_Fungi]
]

### Additional context

Appeared after I updated today, and I update reasonably frequently, so likely caused by a commit in the past 1-3 days.

**Comment by actual-nh** [comment]
Ping: @anothersimulacrum?

**Comment by NotDucc** [comment]
Did you recently make this world or is it more than a few days old?

**Comment by anothersimulacrum** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/50203#discussion_r685210753

**Comment by DavisBroda** [comment]
World is a few weeks old, so more than a few days.

**Comment by anothersimulacrum** [comment]
Presumably fixed in https://github.com/CleverRaven/Cataclysm-DDA/pull/49940

**Comment by DeeUnderscore** [comment]
This was filed against a version that includes #49940. I am still experiencing this with 0.F-3026-gbc5fb3d1a7

**Comment by hexagonrecursion** [comment]
[Foster City.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7879316/Foster.City.zip)

1. I generated a save in 8fa3885 with "NATO assault rifle with burst" (id: sig552) and "NATO assault rifle" (id: nato_assault_rifle).
2. I loaded the save in e49949d

 DEBUG    : item 'sig_assault_rifle' has no variant 'sig552'!

 FUNCTION : void item::set_itype_variant(const string&)
 FILE     : src/item.cpp
 LINE     : 8553
 VERSION  : e49949d

![DeepinScreenshot_select-area_20220117085504](https://user-images.githubusercontent.com/52621858/149715393-f2b9b0d8-332b-4e49-9d64-a956c21b37c6.png)

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: 8fa3885 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: e49949d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]
