### ISSUE TITLE
crash after accepting mission twice

### ISSUE THREAD

**Issue by schauveau** [CleverRaven/Cataclysm-DDA#52220]
### Describe the bug

I noticed that, in some rare cases, it is possible to get the same mission twice from an NPC which causes the application to crash.

This is a problem that is present for at least a few weeks in the master version but I only figured out recently how to reproduce it.

### Steps To Reproduce

Most missions work fine but I was able to reproduce it reliably with the JABBERWOCK mission at the start of a refugee scenario. I suspect that the problem could be related to the presence of 'intimidate' choices at the beginning (because they are absent from most mission dialogs).

The dialog starts with "The eater of the dead… something was ripping zombies to shreds and only leaving a few scattered limbs…""

    a: [INTIMIDATE 25%] Drop you weapon!
    b: [INTIMIDATE 15%] Get out of here or I'll kill you
    c: What's the matter?
    d: I don't care

I select 'c', accept the mission and try to reach the trade dialog. That can typically be achieved in 3 more steps: 

    ...
    a: I'll do it
    ...
    a: Not a problem
    ...
    f: Let's trade item

Then I press ESC to exist the trade dialog.

I am now back at the initial menu (see above).

I can then press 'c' and 'a' to accept the mission again.

This triggers the error "strange: player is already assigned to mission 1"

Pressing SPACE or 'i' causes the application to stop.

### Expected behavior

I suspect that pressing ESC in the trade menu should not open the initial menu (the one with the 'intimidate' choices).

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 11 (bullseye); Release: 11; Codename: bullseye; 
- Game Version: 0.F-2993-gdbfb247981 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Graphical Overmap [Graphical_Overmap]
]

**Comment by hexagonrecursion** [comment]
The steps above are unreliable: sometimes there is only one conversation option after saying "a: Not a problem". I did manage to reproduce this once though.

No crash.log was generated

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: 9473cf6 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by schauveau** [comment]
A quick way to reproduce the problem is to make the jabberwok mission mandatory for instance by editing json/npcs/missiondef.json to remove all instances of "ORIGIN_OPENER_NPC" except, of course, in MISSION_KILL_JABBERWOCK. The "origins" field does not like to be empty so in some places you may want to replace it by "ORIGIN_ANY_NPC" instead.

**Comment by LeahLuong** [comment]
I wonder if this is somehow related to #52585. I don't think I accepted the mission twice but I was getting a similar crash w/out log involving the intimidate options. This was on the 3rd mission from the chain that begins w/ the jabberwock.

**Comment by hexagonrecursion** [comment]
> A quick way to reproduce the problem is to make the jabberwok mission mandatory for instance by editing json/npcs/missiondef.json to remove all instances of "ORIGIN_OPENER_NPC" except, of course, in MISSION_KILL_JABBERWOCK.

I used the debug menu to give the mission to an NPC.

Error copied to clipboard:
```
 DEBUG    : strange: player is already assigned to mission 2

 FUNCTION : void mission::assign(avatar &)
 FILE     : src/mission.cpp
 LINE     : 281
 VERSION  : 0.F-4465-gef6206f0f7
```

debug.log:
```c++
-----------------------------------------
13:32:26.504 : Starting log.
13:32:26.504 INFO : Cataclysm DDA version 0.F-4465-gef6206f0f7
13:32:26.504 INFO : [main] C locale set to C.UTF-8
13:32:26.504 INFO : [main] C++ locale set to C.UTF-8
13:32:26.504 INFO : SDL version used during compile is 2.0.18
13:32:26.504 INFO : SDL version used during linking and in runtime is 2.0.18
13:32:26.667 WARNING : opendir [lang/mo/] failed with "No such file or directory".
13:32:26.670 INFO : Number of render drivers on your system: 4
13:32:26.670 INFO : Render driver: 0/opengl
13:32:26.670 INFO : Render driver: 1/opengles2
13:32:26.670 INFO : Render driver: 2/opengles
13:32:26.670 INFO : Render driver: 3/software
13:32:26.675 INFO : [options] C locale set to en_US.UTF-8
13:32:26.675 INFO : [options] C++ locale set to en_US.UTF-8
13:32:26.675 INFO : Setting language to: 'en'
13:32:26.675 INFO : [i18n] Scanning core translations from lang/mo/
13:32:26.675 INFO : [i18n] Scanning mod translations from ./mods/
13:32:26.675 WARNING : opendir [lang/mo/] failed with "No such file or directory".
13:32:26.675 WARNING : opendir [./mods/] failed with "No such file or directory".
13:32:26.780 INFO : Active renderer: 3/software
13:32:26.807 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
13:32:26.920 INFO : Setting language to: 'en'
13:32:26.920 INFO : [i18n] Scanning core translations from lang/mo/
13:32:26.920 INFO : [i18n] Scanning mod translations from ./mods/
13:32:26.920 WARNING : opendir [lang/mo/] failed with "No such file or directory".
13:32:26.920 WARNING : opendir [./mods/] failed with "No such file or directory".
13:32:27.053 WARNING : opendir [./mods/] failed with "No such file or directory".
13:33:04.174 WARNING : opendir [./save/tmp/mods] failed with "No such file or directory".
13:33:30.348 INFO : Loaded tileset: UltimateCataclysm
13:33:30.938 INFO : Loaded tileset: UltimateCataclysm
13:36:25.737 ERROR : (error message will follow backtrace)
    ./with-debug-symbols-cataclysm-tiles(debug_write_backtrace(std::ostream&)+0x23) [0x2936973]
    ./with-debug-symbols-cataclysm-tiles(DebugLog(DebugLevel, DebugClass)+0x166) [0x2936146]
    ./with-debug-symbols-cataclysm-tiles(realDebugmsg(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0xa5) [0x2935be5]
    ./with-debug-symbols-cataclysm-tiles(void realDebugmsg<int&>(char const*, char const*, char const*, char const*, int&)+0x43) [0x2acd5c3]
    ./with-debug-symbols-cataclysm-tiles(mission::assign(avatar&)+0x4b) [0x315282b]
    ./with-debug-symbols-cataclysm-tiles(talk_function::assign_mission(npc&)+0x2f) [0x33b0cbf]
    ./with-debug-symbols-cataclysm-tiles() [0x337eb74]
    ./with-debug-symbols-cataclysm-tiles() [0x337eb27]
    ./with-debug-symbols-cataclysm-tiles() [0x337eaf7]
    ./with-debug-symbols-cataclysm-tiles() [0x337ea62]
    ./with-debug-symbols-cataclysm-tiles(std::function<void (dialogue const&)>::operator()(dialogue const&) const+0x29) [0x3188bb9]
    ./with-debug-symbols-cataclysm-tiles(talk_effect_fun_t::operator()(dialogue const&) const+0x1e) [0x3188b7e]
    ./with-debug-symbols-cataclysm-tiles(talk_effect_t::apply(dialogue&) const+0x93) [0x3366c43]
    ./with-debug-symbols-cataclysm-tiles(dialogue::opt(dialogue_window&, talk_topic const&)+0xb94) [0x335f514]
    ./with-debug-symbols-cataclysm-tiles(avatar::talk_to(std::unique_ptr<talker, std::default_delete<talker> >, bool, bool)+0x3ad) [0x335c40d]
    ./with-debug-symbols-cataclysm-tiles(game::chat()+0xb75) [0x335a375]
    ./with-debug-symbols-cataclysm-tiles(game::do_regular_action(action_id&, avatar&, cata::optional<tripoint> const&)+0x1148) [0x2bbe108]
    ./with-debug-symbols-cataclysm-tiles(game::handle_action()+0x17e) [0x2bc9e8e]
    ./with-debug-symbols-cataclysm-tiles(do_turn()+0x6c8) [0x29c9b98]
    ./with-debug-symbols-cataclysm-tiles(main+0x515) [0x2f3dc35]

    Attempting to repeat stack trace using debug symbols…
    debug_write_backtrace(std::ostream&)
    …/src/debug.cpp:1104
    DebugLog(DebugLevel, DebugClass)
    …/src/debug.cpp:1331
    realDebugmsg(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    …/src/debug.cpp:443
    void realDebugmsg<int&>(char const*, char const*, char const*, char const*, int&)
    …/src/debug.h:?
    mission::assign(avatar&)
    …/src/mission.cpp:?
    talk_function::assign_mission(npc&)
    …/src/npctalk_funcs.cpp:120
    operator()
    …/src/npctalk.cpp:1919
    void std::__invoke_impl<void, talk_effect_fun_t::talk_effect_fun_t(void (* const&)(npc&))::$_115&, dialogue const&>(std::__invoke_other, talk_effect_fun_t::talk_effect_fun_t(void (* const&)(npc&))::$_115&, dialogue const&)
    /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:61
    _ZSt10__invoke_rIvRZN17talk_effect_fun_tC1ERKPFvR3npcEE5$_115JRK8dialogueEENSt9enable_ifIXsr6__and_ISt7is_voidIT_ESt14__is_invocableIT0_JDpT1_EEEE5valueESE_E4typeEOSH_DpOSI_
    /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:156
    std::_Function_handler<void (dialogue const&), talk_effect_fun_t::talk_effect_fun_t(void (* const&)(npc&))::$_115>::_M_invoke(std::_Any_data const&, dialogue const&)
    /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:291
    std::function<void (dialogue const&)>::operator()(dialogue const&) const
    /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:560
    talk_effect_fun_t::operator()(dialogue const&) const
    …/src/dialogue.h:172
    talk_effect_t::apply(dialogue&) const
    …/src/npctalk.cpp:3577
    dialogue::opt(dialogue_window&, talk_topic const&)
    ??:?
    avatar::talk_to(std::unique_ptr<talker, std::default_delete<talker> >, bool, bool)
    …/src/npctalk.cpp:939
    game::chat()
    ??:?
    game::do_regular_action(action_id&, avatar&, cata::optional<tripoint> const&)
    ??:?
    game::handle_action()
    …/src/handle_action.cpp:2838
    do_turn()
    …/src/do_turn.cpp:695
    main
    …/src/main.cpp:711
Backtrace emission took 14 seconds.
(continued from above) ERROR : src/mission.cpp:281 [void mission::assign(avatar &)] strange: player is already assigned to mission 2
```

gdb trace of the crash:
```c++
Thread 1 "with-debug-symb" received signal SIGSEGV, Segmentation fault.
0x00007467f7da2cd2 in __memmove_ssse3_back () from /lib64/libc.so.6
(gdb) bt
#0  0x00007467f7da2cd2 in __memmove_ssse3_back () from /lib64/libc.so.6
#1  0x0000000002613d2d in std::__copy_move<true, true, std::random_access_iterator_tag>::__copy_m<mission*> (__first=0x3e557fb8, __first@entry=0x7f20ba0, __last=<optimized out>, __last@entry=0x7f20b98, __result=0x7f20b98) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/stl_algobase.h:431
#2  0x0000000002613d06 in std::__copy_move_a2<true, mission**, mission**> (__first=0x3e557fb0, __first@entry=0x7f20ba0, __last=0x3e557fb8, __last@entry=0x7f20b98, __result=0xffffffffc99c8ae0) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/stl_algobase.h:494
#3  0x0000000002613cd6 in std::__copy_move_a1<true, mission**, mission**> (__first=0x3e557fb0, __first@entry=0x7f20ba0, __last=0x3e557fb8, __last@entry=0x7f20b98, __result=0xffffffffc99c8ae0) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/stl_algobase.h:522
#4  0x0000000002613c74 in std::__copy_move_a<true, __gnu_cxx::__normal_iterator<mission**, std::vector<mission*, std::allocator<mission*> > >, __gnu_cxx::__normal_iterator<mission**, std::vector<mission*, std::allocator<mission*> > > > (__first=__first@entry=0x21, __last=..., __result=__result@entry=0x0) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/stl_algobase.h:530
#5  0x0000000002613c29 in std::move<__gnu_cxx::__normal_iterator<mission**, std::vector<mission*, std::allocator<mission*> > >, __gnu_cxx::__normal_iterator<mission**, std::vector<mission*, std::allocator<mission*> > > > (__first=__first@entry=0x21, __last=..., __result=<error reading variable: Cannot access memory at address 0xffffffffc99c8ae0>) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/stl_algobase.h:652
#6  0x0000000002613b27 in std::vector<mission*, std::allocator<mission*> >::_M_erase (this=this@entry=0x3b094f58, __position=0x0) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/vector.tcc:175
#7  0x000000000260bbbb in std::vector<mission*, std::allocator<mission*> >::erase (this=this@entry=0x3b094f58, __position=0x0) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/stl_vector.h:1431
#8  0x00000000033b0d1c in talk_function::assign_mission (p=...) at src/npctalk_funcs.cpp:122
#9  0x000000000337eb74 in talk_effect_fun_t::talk_effect_fun_t(void (* const&)(npc&))::$_115::operator()(dialogue const&) const (this=<optimized out>, this@entry=0x7efbea0, d=...) at src/npctalk.cpp:1917
#10 0x000000000337eb27 in std::__invoke_impl<void, talk_effect_fun_t::talk_effect_fun_t(void (* const&)(npc&))::$_115&, dialogue const&>(std::__invoke_other, talk_effect_fun_t::talk_effect_fun_t(void (* const&)(npc&))::$_115&, dialogue const&) (__f=..., __args=...) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:61
#11 0x000000000337eaf7 in std::__invoke_r<void, talk_effect_fun_t::talk_effect_fun_t(void (* const&)(npc&))::$_115&, dialogue const&>(talk_effect_fun_t::talk_effect_fun_t(void (* const&)(npc&))::$_115&, dialogue const&) (__fn=..., __args=...) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:154
#12 0x000000000337ea62 in std::_Function_handler<void (dialogue const&), talk_effect_fun_t::talk_effect_fun_t(void (* const&)(npc&))::$_115>::_M_invoke(std::_Any_data const&, dialogue const&) (__functor=..., __args=...) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:291
#13 0x0000000003188bb9 in std::function<void (dialogue const&)>::operator()(dialogue const&) const (this=this@entry=0x7efbea0, __args=...) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:560
#14 0x0000000003188b7e in talk_effect_fun_t::operator() (this=0x7efbea0, d=...) at src/dialogue.h:171
#15 0x0000000003366c43 in talk_effect_t::apply (this=0x7ffca9c88aa0, d=...) at src/npctalk.cpp:3578
#16 0x000000000335f514 in dialogue::opt (this=<optimized out>, this@entry=0x7ffca9c88f08, d_win=..., topic=...) at src/npctalk.cpp:1831
#17 0x000000000335c40d in avatar::talk_to (this=<optimized out>, this@entry=0x712b420, talk_with=..., radio_contact=<optimized out>, is_computer=<optimized out>) at src/npctalk.cpp:938
#18 0x000000000335a375 in game::chat (this=0x712afc0) at src/npctalk.cpp:665
#19 0x0000000002bbe108 in game::do_regular_action (this=this@entry=0x712afc0, act=@0x7ffca9c89a14: ACTION_CHAT, player_character=..., mouse_target=...) at src/handle_action.cpp:2069
#20 0x0000000002bc9e8e in game::handle_action (this=0x712afc0) at src/handle_action.cpp:2838
#21 0x00000000029c9b98 in do_turn () at src/do_turn.cpp:695
#22 0x0000000002f3dc35 in main (argc=<optimized out>, argv=<optimized out>) at src/main.cpp:711
```
errors printed on the stdout or stderr:
```
malloc(): unaligned tcache chunk detected
malloc(): unaligned tcache chunk detected
malloc_consolidate(): invalid chunk size
malloc(): unaligned tcache chunk detected
```

**Comment by schauveau** [comment]
I got the double mission and the crash from the mission "Find Antibiotics". 
That may just be a coincidence but there was also a few red choices in the first menu.

**Comment by hexagonrecursion** [comment]
/confirned

note: I am flagging this as confirmed based on the above information. I did **not** redo the test. It is possible that this might have been fixed since

**Comment by hexagonrecursion** [comment]
/confirmed

sorry I have mistyped the command

**Comment by Cimanyd0** [comment]
Still happening. Some starting NPCs look like this when you first talk to them:

![At least we've got shelter](https://user-images.githubusercontent.com/74877667/173283902-b9c19142-d11a-42f4-9cf0-91ac9dca2091.png)

In these cases, there is no bug. To get a mission, you have to `Can I do anything for you?` Asking to trade and hitting Esc returns you to the menu pictured above, and asking for a mission again gets `"I don't have any more jobs for you."`

Some starting NPCs have something to say immediately (about their quest) when you first talk to them:

![I can't believe it happened](https://user-images.githubusercontent.com/74877667/173284310-15453aa3-6a8a-4916-8c21-3ab953333946.png)

In this case, you can accept the mission, go to the normal screen in the first picture, open the trade window, Esc, and you end up back here.

![Deja vu](https://user-images.githubusercontent.com/74877667/173284969-1bc1f446-c12a-4e7f-9263-4feddff4e63a.png)

Accepting the mission a second time results in an error followed by a crash.

![An error has occured](https://user-images.githubusercontent.com/74877667/173285664-9db65c9f-19be-45bc-bbca-72fdb346cf9f.png)

The mission that gave me this bug (and I saw again trying to reproduce it, as seen in the screenshots) was the zombie mom. This issue was about the jabberwock mission. #54648 is about the asthmatic.

- OS: Windows
    - OS Version: 10.0.19043.1706 (21H1)
- Game Version: 781a1fc [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Cimanyd0** [comment]
Leaving the trade window sends you back to whatever the NPC says when you first press C. It should probably send you back to the `"At least we've got shelter."` where you asked to trade in the first place. Here's what happens when you have accepted one of the missions that doesn't have this issue, and the NPC wants to ask you about it whenever you talk to them:
![CDDA bugged NPC 4](https://user-images.githubusercontent.com/74877667/173441867-267ea209-cc88-481e-aab6-e3cab5565a15.png)

(this one doesn't cause an error or crash, since it doesn't let you accept a mission twice)
