### ISSUE TITLE
Slimes reproduce infinitely

### ISSUE THREAD

**Issue by Balthasar-eu** [CleverRaven/Cataclysm-DDA#53565]
### Describe the bug

I did a labstart, the game got progressively slower and as soon as I reached the lab surface it was completely filled with slime. I don't know if it is expected behavior for slimes to multiply on their own, but I found an old bug report from June: https://github.com/CleverRaven/Cataclysm-DDA/issues/49186 where the same problem seems to be seen as a bug. For that issue the underlying problem was already identified and fixed so I am opening a new report.
I assume the problem is related to the splitting and merging behavior of slimes.

The slimes seem to be somewhat stable when undisturbed, but can reproduce rapidly under the right circumstances. I base that on an instance when I opened a door leading to a room filled with slime and retreated to not get overwhelmed, I could, however, witness through glass walls, how in the neighbouring room slime started to appear out of nowhere (I assume new slime spawns did not find a place to appear in the original room and the nearest free space was through the wall). After a few in game minutes the previously empty room had been completely filled with small and tiny slimes.

### Steps to reproduce

1. Do a labstart
2. Sleep
3. find slime room/ Surface of large research facility

### Expected behavior

If slimes are supposed to reproduce by themselves maybe there should be a limit of how many slimes can be in a certain area to prevent a complete slime overlow. If this is a consequence of the splitting and merging behaviour, I would expect the sum of slime mass to be kept equal.

### Screenshots

![slimes](https://user-images.githubusercontent.com/36669346/146653658-01988a25-2f89-48d3-a475-41094001ca9f.png)

### Versions and configuration

cdda-linux-tiles-x64-2021-12-16-1453
[
  "dda",
  "no_npc_food",
  "no_fungal_growth",
  "package_bionic_professions",
  "blazeindustries",
  "stats_through_kills"
]

**Comment by GoLoT** [comment]
After a quick look at the code, it seems that slimes have the following behavior:
* They check all the tiles around.
* If the tile is empty they try to split if their size is > 85. This creates a new small slime with size 50 while reducing the original slime's size by 15. This creates 35 unit of slime from thin air.
* If there is a slime in that tile, they transfer part of their size (5) to the other slime. No issues here. And if the target slime is a brain slime with <50% they sacrifice themselves to heal the brain slime. Again, no issue here.
* If there is a non-slime monster on the tile, they try to convert it into a slime. I don't see any issues here either.
* If there is a player, they are slimed. No size changes.

My conclusion is that the splitting into a nearby tile is creating blob mass out of thin air and slowly creating new small slimes out of nowhere. Also there are no checks to discard impassable tiles, which I think is why sometimes they spawn slimes on the other side of walls. They try to split into a wall, the game tries to find a valid position around it and ends up placing a slime on the other side of the wall. This might also be one of the reasons there are so many debug messages popping up about the game not being able to place monsters and trying to move towards an occupied tile.

I will have a PR ready in a bit.

**Comment by Balthasar-eu** [comment]
I downloaded the experimental from today and killed most slimes in the lab area via debug to see if the problem was fixed, however slimes still started appearing quite fast, but only centered in one specific corner of the map.

(image after a few hours waiting after eradication via debug)
![slimes](https://user-images.githubusercontent.com/36669346/146686461-89e71191-1248-421f-a597-b8eabd55f519.png)

I looked in the floor above that spot and found a skitterbot in an eternal fight against a group of slimes:

![skitterfight](https://user-images.githubusercontent.com/36669346/146686549-60986d73-7efe-4951-9b2a-702f7cf9f525.png)

So what I assume happens is that the skitterbots tazer damage is really slow to kill the slimes, which in turn can't damage the skitterbot at all. When the skitterbot kills a normal sized slime, two healthy small slimes are created which can reform a normal slime, which is big enough to split some if its speed (mass) into a small slime, and after getting killed creates two new small slimes, one of them might not have enough space to be placed in the room, which causes it to fall down a z level, which leads to an agglomeration of slimes below.

I should note, that after I moved the avatar to the skitterbot and waited a while the skitterbot quickly killed all the slimes, so maybe the stalemate is also a result of how combat out of character view is resolved (I don't know if there is actually a difference).

**Comment by GoLoT** [comment]
> two healthy small slimes are created which can reform a normal slime, which is big enough to split some if its speed (mass) into a small slime, and after getting killed creates two new small slimes

This makes sense. I'll take a quick loot at the mdeath effect and see if there is something that can be done.

**Comment by GoLoT** [comment]
@Balthasar-eu I pushed the new fix and it worked fine in my tests. I tried to reproduce your scenario with a skitterbot and multiple slimes and the fix worked well but if you can, repeat your test case when the PR is merged just to make sure.

**Comment by Balthasar-eu** [comment]
Hi, it seems to work well now I could not see any problematic agglomeration of slimes anymore. It does still seem like sometimes slimes will created through walls, because I still encounter solitary small slimes in rooms adjacent to goo pits, but I could never see the slime creation directly.
