### ISSUE TITLE
Jay refers to Cody as both "she" and "they" when you are getting the first mission from them

### ISSUE THREAD

**Issue by AcidAntOnAMinefield** [CleverRaven/Cataclysm-DDA#54652]
### Describe the bug

After you finish the Quest for Cody and Cody asks you to talk to Jay, Jay seems to flop between "she" and "they". On Jay's first dialogue message, the pronoun used is always "they", but on the second message after the player answers with "I'm Listening." Jay refers to Cody as "she" and "her" on the 1st and last lines of the dialogue. 

### Steps to reproduce

1. Finish Cody's quest and talk to Jay as instructed.
2. Read the dialogues.
3. Observe the inconsistency

### Expected behavior

Consistency when it comes to the usage of the pronouns.

### Versions and configuration

- Windows 7
- Build 2022-01-21-0543
- NeoDays
- Dark Days Ahead [dda]
- English

### Additional context

Should add here to what was mentioned above that by "consistency" I mean when referring to one particular individual, the pronouns should remain the same: if they are going be they/them, they should remain they/them and not be referred to as he/she on the sentence immediately after, unless the purpose for the usage of "They/Them" is to conceal the character's Gender - which in this case, it clearly wasn't.

**Comment by LeahLuong** [comment]
Look out! A gender Nazi!

**Comment by AcidAntOnAMinefield** [comment]
> Look out! A gender Nazi!

Um. Okay? Not sure how someone pointing out an inconsistency in dialogue led to that very creative and definitely not edgy remark. But uh... sure?

**Comment by Michael1993** [comment]
It's not really an inconsistency from a non-technical standpoint. If you are bilingual or a non-native English speaker it's fairly common to swap between neutral and gendered pronouns when talking about a person...

**Comment by AcidAntOnAMinefield** [comment]
> It's not really an inconsistency from a non-technical standpoint.

It is an inconsistency. Considering the fact that both characters **are** native English speakers (Unless the Lore was revamped and the game no longer takes place in New England), there's only one potential particular scenario where Jay would refer to Cody as "they", and that would be if she/they were non-binary - which we have really no reason to assume or know whether that's the case. And the giveaway for the fact they *are* native Speakers is in their names too. 

>  If you are bilingual or a non-native English speaker it's fairly common to swap between neutral and gendered pronouns when talking about a person...

And I am not sure I agree with you on the Bilingual/Non-native aspect of that either: I'm not native to the English language, but I speak English and 2 other foreign languages, being "fluent" at all 3 and this does not include my native language. I only use English Gender-Neutral Pronouns referring to 1 (one) individual if I am talking about someone that is non-binary, whether they're active or passive part of the conversation. And this is usually the case in most interactions I've had with several hundreds, probably thousands of people, native to English or otherwise.

**Comment by Michael1993** [comment]
Certain languages don't make a distinction between males or females when talking about a third person. Hungarian (my native language) is one such language. I've heard people (Hungarians, tbh) mix up pronouns a LOT. I do it constantly. Guess your experience is different.

**Comment by AcidAntOnAMinefield** [comment]
I'd wager it may have something to do with the root language yes. 
For clarity, I'm native to Portuguese (european), speak Spanish, French and English fluently. Latin-based languages always seem to refer to third parties by their known/assumed gender as they don't have gender-neutral terms for singular-third person except for their own versions of "it" when applicable which is mostly used for animals and/or inanimate objects of sorts. 

I can understand in your particular case it being correct, and perhaps it will go unnoticed for English natives considering the current cultural aspects of pronouns for specific groups of people. However, the reason I created this specific "issue" is in relation to the English version of the game and in regards to the language itself and the usage of pronouns, irrespective of any cultural aspects that may be brought up. Pronoun consistency is just as important as tense consistency, which is something else that on occasion seems to be ignored.

**Comment by LeahLuong** [comment]
Doesn't the "non" in "non-binary" reference a binary??

Please note, my previous comment was purposely ambiguous. Was I referring to Jay as the gender Nazi for willfully misusing "Cody's" pronouns?? Was I referring to OP as the Nazi for policing Jay's use of pronouns?? Your interpretation of that ambiguity is a chance to examine your own preconceptions &/or biases.

Also, who are we to assume that chars in a game who are mimicking real life conversation will always use perfect grammar & proper tenses. I mean, some of us are like that (I'm not going to say it's me but I'm not not saying that!) but we can't expect it of every1.

Furthermore, _should_ we go about making assumptions concerning individuals' cultural inheritances based on their assumed or given names?? _Should_ we assume every1 in a given geographical region is a speaker of that region's native tongue?? These are rhetorical questions & I leave it to the reader to sort out to whom they are directed.

**Comment by haveric** [comment]
Assuming that the NPC in question goes by the standard gender role, there is no issue at all swapping between she/her and they/them within normal speech even in English. If the NPC is intended to be non-binary, then the she/hers should be replaced, but that would need to be discussed with whoever created these NPCs. From taking a look at the original PR: https://github.com/CleverRaven/Cataclysm-DDA/pull/54022, that does not seem to be the intention.

**Comment by Faalagorn** [comment]
It seems that #56438 will fix that inconsistency.

**Comment by esotericist** [comment]
more to the point, word from the creator in comments on that PR is that the inconsistency was unintentional, and the character wasn't specifically intended to be non-binary. but fortunately, it should be fixed soon enough.

**Comment by AcidAntOnAMinefield** [comment]
Glad to see it was addressed :) 

For the record, I would be perfectly fine with Cody either way, the only point of this "issue" was to just to address the inconsistency and clear it up.

**Comment by esotericist** [comment]
well. it's not addressed yet. that's why i didn't close the issue when i commented on it.

**Comment by NetSysFire** [comment]
Reopening with good first issue since I can confirm it is still present in the dialogue.

**Comment by Fris0uman** [comment]
Fixed in #56438
