### ISSUE TITLE
New FoV narrowing functionality doesn't work properly

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#57417]
### Describe the bug

There's apparently a new functionality in the Experimental I just downloaded that causes the FoV to narrow as you continue to refine the aim. That's a cool functionality, but I immediately encountered two bugs:
1. When nearing the maximum aim at a medium distance, the target is lost as it moves a tile forwards, as it now moves into the invisible area (presumably only when the target isn't at a perfectly aligned orthogonal location). 
2. When giving up the aim because the target moved one step forward, I'm still limited to a rather short circular visibility range around my character for several turns. That should presumably disappear immediately.

### Steps to reproduce

1. Change to the latest experimental because the one used had unlimited ranged electrical zombie attacks.
2. Try to aim at the zombie from a long range to be able to get off a shot with maximum precision before it comes within its now less unreasonable range.
3. Refine the aim one step at a time to fire with maximum precision at a range just beyond that of the zombie.
4. Find that you can't see anything beyond 10 tiles or so except in a jagged line along the sight range.
5. Watch in frustration that your expert marksman loses the target because it had the audacity to move towards him.

### Expected behavior

- Ability to track the target, but lose peripheral vision, which was probably what was intended.
- Restored situational awareness when aiming is broken off.

### Screenshots

Here I've fired a couple of shots at maximum precision at the shocker zombie while sitting on the MC, and then backed away further to be able to fire more shots (or let the bugger bleed out). The FoV narrowing is still present, even though I was above the street corner when the shots were fired, and the center of the lingering awareness bubble isn't even centered at the character...
![Screenshot (241)](https://user-images.githubusercontent.com/22739822/166746854-8cf22931-c870-427b-a471-25dd1a8ec2e9.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1645 (21H1)
- Game Version: f97c81e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

There may be some things that might indicate that this wasn't completely untested:
- It seems the loss of aim only happens when refining the aim manually, one step at a time. At least some full precision shot did hit.
- It seems the loss of situational awareness might be tied to being in/on a vehicle, as it seems to be restored as I move off my MC, but not while waiting or starting and driving.
- I looked through the settings, but didn't find a way to disable the feature until it works properly. It wouldn't be the first time I missed something, though.

Edit: The FoV center jumped around when moving towards the dead zombie (on the MC). At a guess, it's tied to a map tile location, and might be the local map tile coordinates where the view was formed, never updated as the character doesn't relative to the vehicle, but it's the vehicle doing the moving, so it jumps as to the corresponding coordinates of the new tile. Note that it's just a guess, as I haven't done any testing beyond this observation.

Edit 2: Firing a bow at zombies within the local awareness bubble DOES open up the awareness after the shot (with manual aim refinement, while still sitting on the MC). I don't know if it's tied to a different weapon (bow rather than rifle), or the range being outside of the bubble when it doesn't clear.

**Comment by Termineitor244** [comment]
> 1. When nearing the maximum aim at a medium distance, the target is lost as it moves a tile forwards, as it now moves into the invisible area (presumably only when the target isn't at a perfectly aligned orthogonal location).

/confirmed

![imagen](https://user-images.githubusercontent.com/53200489/166810685-4cbfc1d2-7246-4ede-8231-5359964a2a0d.png)

There are some problems with the new FoV, this screenshot is from me aiming at a zombie that moved one tile into "the invisible" so I'm no longer aiming at it and can't fire until it appears again.

**Comment by toweroglass** [comment]
I think there should be a limit to how "tight" the fov gets. or some other way of visualizing focus that doesn't limit your entire view to just the small awareness bubble around you.

**Comment by bombasticSlacks** [comment]
This was already fixed last night lol

**Comment by PatrikLundell** [comment]
Unfortunately, it's only partially fixed. Sitting on a MC firing, and then backing to get off a new shot does not clear the FoV restriction. Here I've backed off a bit from the bunch of Mi-gos to get off a new shot (you can see the casings from the previous location):
![Screenshot (243)](https://user-images.githubusercontent.com/22739822/167164943-a6c8fd92-c5b3-46ec-add2-3c37e49d3db9.png)

- OS: Windows
    - OS Version: 10.0.19043.1645 (21H1)
- Game Version: 30c8dc3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
