### ISSUE TITLE
Crash upon full description search in crafting recipe list

### ISSUE THREAD

**Issue by eturner** [CleverRaven/Cataclysm-DDA#58407]
### Describe the bug

An immediate crash from searching for anything with the 'd:' prefix in the crafting recipes menu. I noticed it several days ago, but I had for some reason compiled it without backtrace and didn't have a crash log until today. Still happens today in a new world, only one commit out of date.

### Steps to reproduce

Craft items: &
Filter: f, F, or /
Search with 'd:'
- e.g. 'd:reach attack"

### Expected behavior

results

### Versions and configuration

OS: Arch
Version: Lines up with experimental build 2022-06-13-1158, coincidentally
Language: English
Graphics: Tiles
Mods: Disable NPC Needs, No Fungal Growth, Bionic Professions

### Additional context

[logs.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8894587/logs.zip)
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8894590/save.zip)

**Comment by BrettDong** [comment]
Cannot reproduce the crash on macOS, Tiles.

**Comment by eturner** [comment]
I just downloaded the experimental build and copied my config and save file over, and it no longer crashes when I do the search. This is the only crash in so many worlds I've played since I've been back into it. No idea what's wrong with my builds.
Disregard I guess. My bad.

**Comment by BrettDong** [comment]
How did you build from source code?

**Comment by eturner** [comment]
I modified the cataclysm-dda-git PKGBUILD from the aur. Only adding the LTO flag and enabling json linting. And the Makefile always decides to compile with -Os so I just sed replace it with -O3 in the prepare.
I'm going to compile it with debug enabled to hopefully figure this out because the fonts look better in my builds for some reason.
[cataclysm-dda-git.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8900926/cataclysm-dda-git.zip)

**Comment by BrettDong** [comment]
I tried patching `Makefile` to replace `-Os` with `-O3` and compiled the game with `make RELEASE=1 LTO=1 cataclysm -j4` on latest Arch Linux (GCC 12.1), and I'm still unable to reproduce the crash. There might be something specific to the AUR build that's related to the crash.

**Comment by eturner** [comment]
Yeah my old potato definitely struggled to compile with debugging symbols enabled.
Probably unrelated, but the fonts look worse with the official build with either data dir, and with my build with the official data dir. My build with my data dir looks better for some reason.
Here's a trace from gdb
[gdb.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/8903212/gdb.txt)

**Comment by NetSysFire** [comment]
>Probably unrelated, but the fonts look worse with the official build with either data dir

worse how? I have a friend which tried cdda on windows and got blurry fonts with directx in tiles. probably a vastly different issue though, but vaguely similar to #37937

**Comment by eturner** [comment]
I guess it's just a font that I don't like as much lol. 
If the fonts in fonts.json are in order of priority, then it fails to load terminus when I start cataclysm-tiles without a terminal. All the configs are the same but the fonts were different when I launch from the terminal or the applcation launcher and I thought it was a rendering error.

**Comment by BrettDong** [comment]
The font issue is related to the version of `freetype` library linked against. FreeType 2.11 refuses to render the Terminus font shipped with the game.

**Comment by Void-0000** [comment]
I'm having the same problem on 0.F, which I got from the AUR, and I'm using EndeavourOS.

**Comment by BrettDong** [comment]
> I'm having the same problem on 0.F, which I got from the AUR, and I'm using EndeavourOS.
> 
> It also occasionally crashes when filtering in other situations as well (looting zombie corpses, getting items from a vehicle trunk, etc) but I haven't found a pattern to that and the same situation that caused a crash once before can also work just fine.

Could you attach a stack trace at crash?

**Comment by NetSysFire** [comment]
Might be #51895. That problem is fixed in experimental quite a while already. Unfortunately since 0.G is so close it is highly unlikely fixes get backported.

I am on vanilla Arch (no derivative) and can neither reproduce with a matching string nor gibberish that wont match anything. But searching with d: still takes ages.

**Comment by eturner** [comment]
> Might be #51895. That problem is fixed in experimental quite a while already. Unfortunately since 0.G is so close it is highly unlikely fixes get backported.

It's been a while but I have to point out that this still occurs in my builds. I switched to clang with full LTO and the Polly plugin, still happens. Search for "d:reach attack", segfault.

I was reminded to test this again because sometime after I built from the repo on the 11th of this month, something was changed so that I crash when sleeping. Appears to be right before I wake up from sleep I just segfault, and this doesn't happen on the provided experimental builds. I was playing on my own builds for a good few weeks before it happened.

Super weird. No idea what to make of this.

**Comment by TealcOneill** [comment]
Something interesting is happening for me when I try to replicate this issue.
I get this error for a bunch of different food items. Yeast, pickles, sauerkraut, ect.
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/45678006/68e24e9c-4e14-417c-aae3-5d1299737fb0)
I got a text document that I had to copy over to a new text file because I couldn't find the original. As a note, the game did not in fact crash. 
[crashlog.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/15286222/crashlog.txt)
For both of these I get directed to files in the Config folder and yet neither of them do actually exist there when I look. Nor anywhere else on my computer.
I have, exactly no idea what the heck is going on here.

**Comment by NetSysFire** [comment]
It works properly for me and I do not get any errors. Are some items nearby in your case? I am just standing in a random field with basically nothing nearby.

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: cdda-experimental-2024-05-11-0903 d78e605 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by TealcOneill** [comment]
I was on a highway but there was nothing but road and maybe some broken car parts nearby.

**Comment by IdleSol** [comment]
This error has been fixed #73444. Did it appear again or do you have an old version of the game?

**Comment by TealcOneill** [comment]
Fresh install this morning, latest experimental.
OS: Windows
OS Version: 10.0.19045.4291 (22H2)
Game Version: cdda-experimental-2024-05-03-0220 abe3f76 [64-bit]
Graphics Version: Tiles
Game Language: System language []
Mods loaded: [
  Dark Days Ahead [dda],
  Disable NPC Needs [no_npc_food],
  Portal Storms Ignore NPCs [personal_portal_storms],
  Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by IdleSol** [comment]
> cdda-experimental-2024-05-03-0220

Fresh? Update the game https://github.com/CleverRaven/Cataclysm-DDA/releases

**Comment by TealcOneill** [comment]
Yo wtf. How in the... I swear I clicked the download link off the front page after reloading and downloaded the top option for experimental. Well that sucks.
Thanks for pointing that out, guess I'll go do that and recheck stuff.

**Comment by TealcOneill** [comment]
I'm not insane! This is an actual issue.
 #73676

**Comment by TealcOneill** [comment]
@GuardianDll I've tested it several more times on the latest version and I think both issues are gone.
- OS: Windows
    - OS Version: 10.0.19045.4291 (22H2)
- Game Version: cdda-experimental-2024-05-15-0120 731bdaa [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]
