### ISSUE TITLE
Going into Advanced Inventory Management crashes the game

### ISSUE THREAD

**Issue by WreckingAbandon** [CleverRaven/Cataclysm-DDA#59629]
### Describe the bug

Either through the "/" shortcut or by navigating the Actions menu, going into it just crashes me out of the game.

### Steps to reproduce

Just open the Advanced Inventory Management.

### Expected behavior

To not crash at all.

### Versions and configuration

VERSION: 32ee0b1
St12length_error basic_string
STACK TRACE:
# 4: 0x731d9b4100 __cxa_get_exception_ptr
# 8: 0x731b3b2478 std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >::reserve(unsigned long)
# 9: 0x731c0a9960 trim_by_length(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, int)
#10: 0x731c0a9894 trim_and_print(catacurses::window const&, point const&, int, nc_color const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, report_color_error)
#11: 0x731b477838 advanced_inventory::redraw_pane(advanced_inventory::side)
#13: 0x731c3949c4 ui_adaptor::redraw_invalidated()
#14: 0x731b470ec4 advanced_inventory::display()
#15: 0x731b470da4 create_advanced_inv()
#16: 0x731b9af48c game::do_regular_action(action_id&, avatar&, cata::optional<tripoint> const&)
#17: 0x731b9ba740 game::handle_action()
#18: 0x731b81e19c do_turn()
#19: 0x731bc96de0 SDL_main
#20: 0x731d7cb5f0 Java_org_libsdl_app_SDLActivity_nativeRunMain

**Comment by pjf** [comment]
Just got a segfault when trying to wield an item:

```
    ./cataclysm-tiles(debug_write_backtrace(std::ostream&)+0x24) [0x13dcafa]
    ./cataclysm-tiles() [0x13bd754]
    ./cataclysm-tiles() [0x13bd442]
    /lib/x86_64-linux-gnu/libc.so.6(+0x430c0) [0x7f0ec30a20c0]
    ./cataclysm-tiles(map::get_vehicles(tripoint const&, tripoint const&)+0x153) [0x18dfc9d]
    ./cataclysm-tiles(map::get_vehicles()+0x69) [0x18dfb41]
    ./cataclysm-tiles(map::generate_lightmap(int)+0x90c) [0x1874898]
    ./cataclysm-tiles(map::build_map_cache(int, bool)+0x191) [0x19013a1]
    ./cataclysm-tiles(game::draw(ui_adaptor&)+0x51) [0x155e94b]
    ./cataclysm-tiles(ui_adaptor::redraw_invalidated()+0x1c2) [0x1fa34ca]
    ./cataclysm-tiles(inventory_selector::query_string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0xa5) [0x1694e09]
    ./cataclysm-tiles(inventory_selector::query_set_filter()+0x1f) [0x1694f01]
    ./cataclysm-tiles(inventory_pick_selector::execute()+0x119) [0x1698cc5]
    ./cataclysm-tiles() [0x15b8127]
    ./cataclysm-tiles(game_menus::inv::wield(avatar&)+0xce) [0x15be126]
    ./cataclysm-tiles(game::wield()+0x1e) [0x158940e]
    ./cataclysm-tiles(game::do_regular_action(action_id&, avatar&, cata::optional<tripoint> const&)+0x2b96) [0x15ef416]
    ./cataclysm-tiles(game::handle_action()+0x308) [0x15ffd4a]
    ./cataclysm-tiles(do_turn()+0x7c0) [0x145fd8b]
    ./cataclysm-tiles(main+0x1121) [0x18d3c05]
```

Which may have the same underlying cause. My most recent set of merges, and thus most likely culprits, are:

```
      You've Got Mail (#59325)
      Add skill achievement requirement descriptions (#59575)
      add overmap auto-note only if the tile is revealed, not everytime it is seen (#59583)
      Wrap text in widget/sidebar help (#59592)
      few quick tailoring material fixes (#59594)
      Remove HELMET_COMPAT (#59604)
      Expand snippets on signs and graffiti (#59602)
      Correct basecamp scanning + made basecamp fakes available as scanned (#59605)
      Flush mapbuffer in overmap_terrain_coverage (#59488)
      Inherit Flags Unit Test (#59617)
      Move vehicle part migrations to json
      fix tests to respect removed additional newline at end of multiline widgets
      multiline wigdets took one line too much; do not add newline at end of rows
```

**Comment by pjf** [comment]
And another while moving:

```
    ./cataclysm-tiles(debug_write_backtrace(std::ostream&)+0x24) [0x13dcafa]
    ./cataclysm-tiles() [0x13bd754]
    ./cataclysm-tiles() [0x13bd442]
    /lib/x86_64-linux-gnu/libc.so.6(+0x430c0) [0x7ff6fa8dc0c0]
    ./cataclysm-tiles(map::get_vehicles(tripoint const&, tripoint const&)+0x153) [0x18dfc9d]
    ./cataclysm-tiles(map::get_vehicles()+0x69) [0x18dfb41]
    ./cataclysm-tiles(map::scent_blockers(std::array<std::array<bool, 132ul>, 132ul>&, std::array<std::array<bool, 132ul>, 132ul>&, point const&, point const&)+0x428) [0x19025e2]
    ./cataclysm-tiles(scent_map::update(tripoint const&, map&)+0xe1) [0x1ec0d1d]
    ./cataclysm-tiles(do_turn()+0x96c) [0x145ff37]
    ./cataclysm-tiles(main+0x1121) [0x18d3c05]
    /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7ff6fa8bd0b3]
    ./cataclysm-tiles(_start+0x2e) [0x101f15e]
```

**Comment by pjf** [comment]
Reverted #59488 and things seem to be stable once more.

**Comment by Zireael07** [comment]
Based on some more reports, I think AIM is the red herring here (people have crashes while saving, too)

**Comment by mlange-42** [comment]
Even trying to open the options in-game crashes for me, consistently.

**Comment by snipercup** [comment]
No issues on version - OS: Windows
    - OS Version: 6.3 9600
- Game Version: 32ee0b1 [64-bit]
So revert to that until it is fixed. Andrei8l already spotted the cause in a comment in #58501

**Comment by WreckingAbandon** [comment]
It seems that this ain't gonna be fixed anytime soon. How do I download the version without this problem for the android version?

**Comment by pjf** [comment]
@WreckingAbandon : If you haven't tried the latest experimental, please do. This was probably fixed in #60018, which patches the cause of a number of odd errors.

(If that does fix it, we can close this bug!)

**Comment by WreckingAbandon** [comment]
I just updated and tried ot out. It still crashes unfortunately.
