### ISSUE TITLE
Attempting to wield or wear an item from the Pickup menu will cause a CTD if you can't fit it into your inventory

### ISSUE THREAD

**Issue by Ilysen** [CleverRaven/Cataclysm-DDA#62314]
### Describe the bug

See title. The game will hang and then close when you try to wield or wear an item in this manner.

### Steps to reproduce

1. Find an item that you can wield/wear but not fit into your inventory. A big thing like a 60 L tank usually works.
2. Use the pickup menu (default hotkey `g`) for that tile. Try to `w`ield it or `W`ear it.
3. CTD and cry.

### Expected behavior

You should be able to wield or wear items from the world without crashing the game.

### Screenshots

N/A - see `Additional context`

### Versions and configuration

You'll notice that the version is dirty; I compile my game from source when I play/code/etc, and this happened on a branch for an existing PR I've got. The master commit it's based on, however, is `f6e4f2f`.

- OS: Windows
    - OS Version: 10.0.19044.2251 (21H2)
- Game Version: 0.F-12437-g082aba1ce0-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Blaze Industries [blazeindustries],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations]
]

### Additional context

This appears to be caused by #62226. Rolling back the changes to `inventory_ui.cpp` stops the issue from happening.

![devenv_uVnC0lNzR3](https://user-images.githubusercontent.com/47678781/202931410-84fc9593-948f-4f56-be3d-312810f6f963.png)

![image](https://user-images.githubusercontent.com/47678781/202931406-098e90bf-36cd-4ddd-9ef3-834df972da3b.png)

I'm attaching my save file I used to verify this bug, although you probably won't need it:
[Sidney.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/10050968/Sidney.zip)

And here's the `debug.log`, although it's cluttered from a bunch of previous runs I was doing for testing of other bugs:
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/10050961/debug.log)

**Comment by DSeyka** [comment]
Can confirm, I was just about to report this as well.

**Comment by andrei8l** [comment]
Model bug report

**Comment by aleksandrtikh** [comment]
It's the case for any greyed-out item. Same thing happens with too heavy items and liquids.

**Comment by Luthaar** [comment]
It still didn't get fixed with the latest experimental version, hope this gets fixed soon

**Comment by Wishbringer** [comment]
The current patch doesn't fix the CTD when trying to select liquids.

**Comment by andrei8l** [comment]
> The current patch doesn't fix the CTD when trying to select liquids.

<details>
<summary>
I can't reproduce. You should make comments about the patch on the PR rather than here.</summary>

![Screenshot from 2022-11-21 14-27-04](https://user-images.githubusercontent.com/68240139/203055194-58b98ae6-0084-45e5-a6f8-693a4319d7b3.png)
</details>

**Comment by Wishbringer** [comment]
@andrei8l: Looks like you are trying to directly wield the item not select it?

**Comment by andrei8l** [comment]
What are the exact steps? Tell me the exact keys you press to get the crash please

**Comment by andrei8l** [comment]
I've added F7 to `Marked/unmark selected item` and I still cannot reproduce the crash.

> Expected behavior is a + prefix instead of the -.

Are you sure? I cannot reproduce this for liquids with yesterday's build either. Liquids are not supposed to be selectable at all.

**Comment by Wishbringer** [comment]
Not frozen no, It's possible my problem is due to an interaction with other yet unmerged PRs.
Maybe the problem is in function `inventory_multiselector::toggle_entries` as there is another instance of `std::vector<inventory_entry *> selected` there (pure guess)?

**Comment by Wishbringer** [comment]
Tried reverting PR #62226 and that fixed the problem for me.
Will try making changes to the function mentioned in my previous post above to attempt a fix locally next.
