### ISSUE TITLE
[Magiclysm] Mage blade and Mage Armor don't work

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#64368]
### Describe the bug

The scaling damage/armor on Mage Blade and Mage Armor isn't applied. Mage Blade only does it's base 12 damage and Mage Armor provides no protection from physical attacks whatsoever.

### Attach save file

Trivially reproducible

### Steps to reproduce

- Give self spells at max level
- Cast both
- Fight zombie

### Expected behavior

The enchantment is applied and the items work as described.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2006 (22H2)
- Game Version: 53f9146 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mythical Martial Arts [MMA]
]

### Additional context

At first I thought the Mage Armor thing was because the sign was inverted (ARMOR_[BLANK] enchantments should be negative to reduce damage), but that should _increase_ damage rather than do nothing, and since the blade isn't working either I assume something more fundamental is broken.

**Comment by GuardianDll** [comment]
\confirmed
![image](https://user-images.githubusercontent.com/67688115/226125786-a611ec2f-7ae5-4a3d-8275-75cd9b09c66e.png)

also heck i forgot i need negative value for armor, need to redo this part

**Comment by SittingDucken** [comment]
Believe mage armor needs the relic_data k, v. As already mentioned the * const:-1 for damage reduction. And potentially items duplicated to account for mage armor/blade +.

**Comment by GuardianDll** [comment]
Oh, that's right
i wonder why the game silenty ignored the fact there is no relic_data

**Comment by SittingDucken** [comment]
Bet without digging.. well formed json is passing through the json check. Since it's a proper field, but doesn't apply to an object, there's no reason to fail when loading the object. Would need a check for dependency, or null application to validate.

**Comment by GuardianDll** [comment]
The reason it silently fails is in #64438

**Comment by SittingDucken** [comment]
Welp there it is 🗡️ 
Question then for these items not working. Would we see better functionality if we transfer the relic data to an enchantment similar to how Gaia's Chosen terra armor is working?
`"relic_data": { "passive_effects": [ { "id": "mgc_ench_magesword" } ] }`

**Comment by GuardianDll** [comment]
It should work exactly the same
Maybe its a good idea to transfer them all (and also add name and description to describe what they do), but i doubt it will resolve the issue

**Comment by SittingDucken** [comment]
Got a few minutes. Will write it out and see if it's any better.

**Comment by SittingDucken** [comment]
```
 {
    "type": "enchantment",
    "id": "mgc_ench_mageblade",
    "has": "WIELD",
    "condition": "ALWAYS",
    "name": { "str": "Holy Illumination" },
    "description": "The light radiating from this weapon cuts with ease.",
    "values": [ { "value": "ITEM_DAMAGE_CUT", "add": { "arithmetic": [ { "u_val": "spell_level", "spell": "holy_blade" } ] } } ]
  }
```

**Comment by SittingDucken** [comment]
That did it. Again guessing, likely an interaction between items and players isn't able to check spell_level appropriately. Since the item can be held by anyone, there's some interaction missing there. Adding it as an enchantment that applies to the player seems to resolve the issue.

That's the fix anyways, if no one gets to it I'll try to put a PR in the next few days to weeks... Newborns 👍

**Comment by GuardianDll** [comment]
Interesting
Actually, removing int requirement for armor was mostly for balance reasons, the weapon still can have this int bonus, in one way or another

**Comment by bombasticSlacks** [comment]
Resolved by #64800

**Comment by KNGRON** [comment]
Updated to latest experimental expecting the mage blade and mage armor issue to be fixed, but I still get pitiful mage blade damage and zero protection mage armor. 
![image](https://user-images.githubusercontent.com/130182575/230668962-a77cb9bc-d403-4b6f-b026-9f2316a0e052.png)
I also created a new world, with only magiclysm as the mod, created a new character and debugged spell level 1 mage blade, cast it, noted the stats, and then debugged spell level 15 mage blade and cast it, and both have the same 11 bash 1 cut damage.

**Comment by GuardianDll** [comment]
You should test the damage and armor, not the UI. The fact that enchantments do not show their values in the UI is a know issue

**Comment by GuardianDll** [comment]
Can't reproduce anymore, the bug is fixed
![image](https://user-images.githubusercontent.com/67688115/230672572-b3f87f12-0b9f-4790-8bca-a829f243bed3.png)

**Comment by KNGRON** [comment]
Did a debug test attacking with a level 15 blade and then a level 1 blade, and got what seem like identical results damage wise on my end. 
![image](https://user-images.githubusercontent.com/130182575/230672855-7a878060-aef2-45fe-bd3c-4378ddd57a39.png)

**Comment by GuardianDll** [comment]
![image](https://user-images.githubusercontent.com/67688115/230673085-29695d01-82e4-4337-9732-a22ee4c49e77.png)

**Comment by KNGRON** [comment]
Strange. I get INT scaling, but not spell level scaling. Is there anything in particular in the update process that might "skip" the actual fix on my end? I use the catapult launcher.

**Comment by GuardianDll** [comment]
idk, but my version is 4 hours old

**Comment by KNGRON** [comment]
Same, I am on version fef3110 which is the 4 hour old one. I will try owerwriting the mod files to see if it's an issue in the update process.

**Comment by GuardianDll** [comment]
it's not the mod files definitely, the issue was with the code itself

**Comment by KNGRON** [comment]
Thank you for the heads up, saves me a lot of trial and error. I will try a fresh download of C;DDA and see if the problem persists to narrow down the cause.

**Comment by KNGRON** [comment]
A fresh install does not have the issue, with the level 1 and level 15 mage blade having around a 10-15 point difference in damage output. Obviously just an issue on my end.
