### ISSUE TITLE
Freshly dug shallow pits outside viewing range glitch

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#64972]
### Describe the bug

![image](https://user-images.githubusercontent.com/59517351/230807972-64954898-1356-4aa3-8190-7da17941d7a5.png)

Not a new bug but I finally got around to reporting it. Tileset is RetroDays, but this is not tileset specific and looks the same in e.g Ultica. When going outside to look at the pits, they do look correctly.

### Attach save file

[Playtesting-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11186872/Playtesting-trimmed.tar.gz)

Note: If you can safely ignore any errors about civilian monsters that do not exist because as the save file name says, I have been playtesting a PR of mine.

### Steps to reproduce

1. Dig some pits outside a building, e.g the evac shelter.
2. Go inside, so the pits will remain in map memory only.
3. They corrupt, but only freshly dug ones?

### Expected behavior

They look the same as when they are actively in your line of sight.

Minor graphical bug. Not gamebreaking or too annoying.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.G [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by TealcOneill** [comment]
@GuardianDll Can't replicate, looks like it was fixed by #65954.

**Comment by NetSysFire** [comment]
I saw this just recently in a run of mine. I am still not sure of the exact replication steps but I am fairly sure its still there.

**Comment by TealcOneill** [comment]
I'll contact you in the future! Thank you.
That's interesting, I wasn't able to replicate this issue with your save or a new one of my own. I don't know why it wouldn't happen in my saves.

- OS: Windows
    - OS Version: 10.0.19045.4291 (22H2)
- Game Version: cdda-experimental-2024-05-15-1833 7f06e9f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by NetSysFire** [comment]
I think this might be a more complex combination of steps and I am still not sure how to reproduce it consistently. I suspect sleeping (and thus going prone) and potentially reloading a save playing a role in this but I have not found steps that work every time yet.
