### ISSUE TITLE
'Apis' NPC can be disarmed of their 'wielded' Sclerotin Claws, which can then be looted and permanently equipped as integrated armor

### ISSUE THREAD

**Issue by Zarhon** [CleverRaven/Cataclysm-DDA#67958]
### Describe the bug

The 'Apis' NPC, the bee-guys you find trapped in Mi-Go cages or as the boss of a mutant giant beehive, has 'Sclerotin Claws', an integrated armor, equipped. 

Since they're an NPC, they can be disarmed, which will cause them to drop the claws. You can then pick them up (which prompts the 'this is stealing' message).

Picking them up has them become stuck in your inventory - they're no listed in any drop item menu but are clearly present in other inventory screens. If you 'Wear' the claws, they are added to the 'integrated' slot as hand armor, potentially conflicting with other armor.

### Attach save file

N/A

### Steps to reproduce

1.  Find or spawn the 'Apis' NPC. They're always in the center of a mutant beehive.
2. Disarm the NPC (move adjacent, interact, choose 'disarm'. Repeat until successful.
3. Pick up the dropped 'Sclerotin Claws'. You'll be told this is stealing, but who cares.
4. Attempt to drop the 'Scleriton Claws', which are now in your inventory, listed as an armor.
5. Wear the 'Sclerotin Claws'. They will become an integrated armor.

Alternately, just debug spawn the Sclerotin Claws (integrated armor) and pick them up. You can have more than one!

### Expected behavior

I can't whack off a mutant-bee person's claws/hands off, and they don't permanently attach to my hands if I do.

### Screenshots

Before disarm
<img width="378" alt="Screenshot_6" src="https://github.com/CleverRaven/Cataclysm-DDA/assets/39234303/e5187d79-456a-4a18-bfde-9697f8856eee">
After disarm, the claws land nearby, ignoring walls somehow
<img width="1205" alt="Screenshot_7" src="https://github.com/CleverRaven/Cataclysm-DDA/assets/39234303/27620187-97f5-4f97-9077-3f63fa616693">
After Disarm
<img width="378" alt="Screenshot_8" src="https://github.com/CleverRaven/Cataclysm-DDA/assets/39234303/46c03ad3-a285-43e3-a3b5-401ab871378b">
Armor layers screen
<img width="1073" alt="Screenshot_2" src="https://github.com/CleverRaven/Cataclysm-DDA/assets/39234303/802fcc31-7881-4613-8659-5f0a555192ef">

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3324 (22H2)
- Game Version: fd60fc1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Stats Through Kills [stats_through_kills],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

**Comment by GuardianDll** [comment]
#73525 supposed to fix it, but i accidentally commited changes it has to #73505, that was merged afterwards
technically resolved by #73505

**Comment by drawsstuff** [comment]
can confirm this is still an issue, just disarmed apis of her claws. using a late august experimental build
![image](https://github.com/user-attachments/assets/3a4d1c9d-460d-48c5-a0d8-8fdb03044060)
![image](https://github.com/user-attachments/assets/6f4c71ea-cbef-4c0a-9aaa-0014ca5e670f)
