### ISSUE TITLE
Defense mode: "Please wait as we build your world" overlaps with settings dialogue

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#73726]
### Describe the bug

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/59517351/7245b957-9e68-4d29-a910-0591f95c8ea4)

### Attach save file

n/a

### Steps to reproduce

1. Make a new world
2. Add defense mode as a mod
3. Create any character.
4. See above screenshot.

### Expected behavior

This modal thing is below the actual fake NPC dialogue.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: cdda-experimental-2024-05-11-0903 d78e605 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by PGR-14** [comment]
Can confirm, it also isn't exclusive to defense mode, as it also happens w/ this mod: https://github.com/gettingusedto/cdda-portal-storm-frequency-and-size-changer-mod

**Comment by Qrox** [comment]
ImGUI windows can only be rendered on top of everything else. Migrating the NPC dialogue window to ImGUI should fix it.

**Comment by Dlinuigh** [comment]
I think maybe all imgui problems have been solved, since I can't reproduce any.

**Comment by Night-Pryanik** [comment]
Nope, the issue is still here in latest experimental as of 02 December.

**Comment by Dlinuigh** [comment]
Oh, I see, after compiling the latest ncurses version game.

**Comment by Dlinuigh** [comment]
![Image](https://github.com/user-attachments/assets/82fb63c4-dcd0-48e1-b865-462deadd0938)

I don't know how to make ncurses border work in ImTui, so I use these symbols to imitate that. Any idea?

**Comment by Dlinuigh** [comment]
> ![Image](https://github.com/user-attachments/assets/82fb63c4-dcd0-48e1-b865-462deadd0938)
> 
> I don't know how to make ncurses border work in ImTui, so I use these symbols to imitate that. Any idea?

emmm, I think `Box Unicode` will make it.
