### ISSUE TITLE
Laptop and mp3 player use singular units of batteries rather than actual light/medium/heavy battery

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#76258]
### Describe the bug

Laptop and mp3 player use singular unit batteries for their charge. They can be unloaded into your inventory, but can't actually be placed down on the ground, they just disappear if you try.

### Attach save file

[TESTING-trimmed.tar.gz](https://github.com/user-attachments/files/16917090/TESTING-trimmed.tar.gz)

### Steps to reproduce

1. Spawn in laptop or mp3 player or find them
2. Notice laptop and mp3 charge is in singular units of battery

### Expected behavior

Laptop could probably use a medium or heavy battery for default. 
The mp3 player probably default to light battery. 

At least get rid of the singular batteries to standardize everything to use the light/medium/heavy style.

### Screenshots

![image](https://github.com/user-attachments/assets/54d4e823-c04d-4c03-9913-0d231969dc17)
![image](https://github.com/user-attachments/assets/70179b99-b8a0-4d4c-a291-76f2fcdfeef1)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4651 (22H2)
- Game Version: cdda-experimental-2024-09-04-0626 0c909b2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by osuphobia** [comment]
I've fixed it in #76167.

**Comment by CoroNaut** [comment]
I've update to the latest version. I used debug mode to spawn in a laptop, but i still see it using 200/200 single unit batteries. The first image is a flashlight with a medium battery 'magazine'. The mp3 player and laptop don't have this 'magazine' slot. That PR only makes them unable to be unloaded in their current state. Which also means you can't install an actual light/medium/heavy battery mod into the laptop or mp3 player in this instance, because it can't be unloaded to be able to install the mod.

The point of my issue was also more specifically the standardization aspect. Having the mp3 player and laptop spawn with a light/medium/heavy battery 'magazine' like the flashlight is what I mean by standardization.

- OS: Windows
    - OS Version: 10.0.19045.4651 (22H2)
- Game Version: cdda-experimental-2024-09-07-0110 e398be1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]


![image](https://github.com/user-attachments/assets/57ab1b4c-153e-4d4e-836a-bd35617997b9)
![image](https://github.com/user-attachments/assets/3057868d-94fe-479f-9fa3-b86ed70c8d51)
![image](https://github.com/user-attachments/assets/aeaa334e-3c86-405d-ad88-2f096972b9a4)

**Comment by osuphobia** [comment]
They were changed to use internal batteries in #76029

**Comment by CoroNaut** [comment]
Alright, I didn't realize we moved to this default rather than have a standardized battery system.
