### ISSUE TITLE
Interface Display Bug

### ISSUE THREAD

**Issue by ProgKing** [CleverRaven/Cataclysm-DDA#77340]
### Describe the bug

The game interface appears cropped, making it impossible to view full menus.

### Attach save file

[Uploading Wallsboro-trimmed.tar.gz…]()

### Steps to reproduce

1. Start the game.
2. Open and interact with the game menus.

### Expected behavior

The game interface displays fully, without cropping or visual glitches.

### Screenshots

![photo_2024-10-25_22-59-41](https://github.com/user-attachments/assets/15786128-56ad-41b5-9523-72422325c949)
![photo_2024-10-25_22-59-04](https://github.com/user-attachments/assets/b8f88e9b-23f3-48b9-b5d5-40064d52ecaf)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: cdda-experimental-2024-10-25-0415 f633a1b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Hope [no_hope],
    Pixel's Various Fuckery [Pix's Shit],
    World on Fire [World_on_fire],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens],
    Martial Mastery [perk_melee_system],
    Vampiric Stuff [vamp_stuff],
    Translate Complex Dialogue [translate_dialogue],
    Bionic Slots [cbm_slots]
]

**Comment by Termineitor244** [comment]
Please update your game to the next experimental version, this specific problem should have been resolved with #77317, which was merged in exactly the next version after yours.

**Comment by DPurple** [comment]
I'm using 2024-10-25-2317 but this bug still exists
![Uploading cap.PNG…]()

My version is:
- OS: Windows
    - OS Version: 10.0.19045.5011 (22H2)
- Game Version: 0d65968 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Extra Mutated Scenarios [extra_mut_scens],
    Fancy dress [fancy_dress]
]

**Comment by DPurple** [comment]
> Please update your game to the next experimental version, this specific problem should have been resolved with #77317, which was merged in exactly the next version after yours.

I'm using 2024-10-25-2317 but this bug still exists
![cap](https://github.com/user-attachments/assets/ac0973b1-ed33-4387-a9e0-30dc8d60acaa)

My version is:
- OS: Windows
    - OS Version: 10.0.19045.5011 (22H2)
- Game Version: 0d65968 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Extra Mutated Scenarios [extra_mut_scens],
    Fancy dress [fancy_dress]
]

**Comment by ProgKing** [comment]
> > Please update your game to the next experimental version, this specific problem should have been resolved with #77317, which was merged in exactly the next version after yours.
> 
> I'm using 2024-10-25-2317 but this bug still exists ![cap](https://private-user-images.githubusercontent.com/6556448/380354236-ac0973b1-ed33-4387-a9e0-30dc8d60acaa.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MzkwOTUsIm5iZiI6MTcyOTkzODc5NSwicGF0aCI6Ii82NTU2NDQ4LzM4MDM1NDIzNi1hYzA5NzNiMS1lZDMzLTQzODctYTllMC0zMGRjOGQ2MGFjYWEuUE5HP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjZUMTAzMzE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Nzk3NTkzMWJmODk5Y2I5MGY3MWE5NTA1NjkzZmY0ZTgzMGQyOWVmMDRjNDA4YjM5ZGZjNTkxN2M5YWExZDg4ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.SyqJwBe4Iuz1YApXKrXF9HCDVFBAgbTAv9fsS6BwVJY)
> 
> My version is:
> 
> * OS: Windows
>   
>   * OS Version: 10.0.19045.5011 (22H2)
> * Game Version: [0d65968](https://github.com/CleverRaven/Cataclysm-DDA/commit/0d6596840ae019a2421870efd4365a66f12dcf78) [64-bit]
> * Graphics Version: Tiles
> * Game Language: English [en]
> * Mods loaded: [
>   Dark Days Ahead [dda],
>   Disable NPC Needs [no_npc_food],
>   Portal Storms Ignore NPCs [personal_portal_storms],
>   Slowdown Fungal Growth [no_fungal_growth],
>   Extra Mutated Scenarios [extra_mut_scens],
>   Fancy dress [fancy_dress]
>   ]
