### ISSUE TITLE
Auto Drive Crashes Game

### ISSUE THREAD

**Issue by Righty12** [CleverRaven/Cataclysm-DDA#77598]
### Describe the bug

Auto Drive Crashes The Game, Set A Way Point, Put on Autodrive and it crashes, it mostly happens when you load in

### Attach save file

[Avery-trimmed.tar.gz](https://github.com/user-attachments/files/17627527/Avery-trimmed.tar.gz)

### Steps to reproduce

1. Load In, Get Into A Car 2. Set Waypoint then use autodrive, 
(also it's been happening for all of my saves 

### Expected behavior

I'd expect to drive into a desired location and not crash

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.4317 (23H2)
- Game Version: 0.G Stable STEAM [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Monsters [Only_Wildlife]
]

**Comment by RenechCDDA** [comment]
There's no crash log recorded and your listed version is 0.G.

Whatever crash may have happened is almost certainly resolved in the year and a half since then.

**Comment by harakka** [comment]
This can be reopened if you manage to reproduce it on 0.H or experimental

**Comment by Righty12** [comment]
it most certainly isn't "resolved" it still crashes but who cares right? $20, I paid for the shittiest steam version, but who cares that's $20 out of my wallet into yours, I'd assume most of you guys who made this are absolute asshats and fuckwits, but again who cares, you got your $20, so I guess I should go fuck myself.

**Comment by harakka** [comment]
This was already explained to you on Discord but here we go again: no-one you're interacting with here sees a single dime from the Steam version. We don't do the Steam version. If you have beef with the Steam version, go complain on the Steam forums.

What's on Steam is the stable version. It stays as it is, that is what stable means. Meanwhile we fix bugs in the _currently worked on_ versions of the game, which you are free to go download and enjoy on the releases page of this repository, just like everybody else.

**Comment by Righty12** [comment]
And who allowed the Steam version to be put up? dipshit, you can literally tell the single dev who put it down to take it down, or even better just move platforms, instead of using a shitty website, there is literally a option to change stable to unstable on steam you can literally add a branch, that single dev is a fucking freeloader who is literally profiting off of you guys who do work hard.

**Comment by RenechCDDA** [comment]
@Righty12  The license is CC-BY-SA-3.0. Distributing CDDA commercially is allowed by anyone. No "permission" is needed, they only need to follow the licensing. Nor can that license be revoked. You are embarrassing yourself.

**Comment by Righty12** [comment]
In that case, I might as well upload to a Porn website and I'll upload it way more frequently then this shitty dev, And I'll charge people $50 for it, Not doing anything to a freeloader who gives zero support and zero help, it's a shitty way of being lazy, if you can't take feedback, you should consider another field of work, and no I don't mean moderate discord servers, I mean if the dev team wants support why don't they get a job, instead of relying on meaningless "donations" that don't go towards anything, I mean honestly you guys are sacks of shit, who can't seem to comprehend common sense but what do I expect from a lousy dev team that allows random assholes to shit on their work, but again maybe you really can't do anything because you are bound by your body weight and can't fit in the shower, take a look at "Indie Stone" creators of Project Zomboid, they actually care for there team and there players, they made a good game, yet you guys can't even code a simple fucking pixel game.

**Comment by Aerin-of-the-Toast** [comment]
the devs do this as a hobby ya goober
