### ISSUE TITLE
Game freezes 100% ram usage

### ISSUE THREAD

**Issue by kholat** [CleverRaven/Cataclysm-DDA#78941]
### Describe the bug

Walk out of the church upwards and a bit to the right, towards Lecia Andrews on the map, eventually the game gets stuck.
The game fails to create a minimized save archive. Zipped save is 33MB max allowed is 25, so I uploaded it to mega. https://mega.nz/file/9mBhwRQZ#GPNx53aV4ctnxUauaan79zvGfAdOk_2moQB382An4gA

I guess it could be NPC loading in or some-such?

### Attach save file

Attached link

### Steps to reproduce

1.Get out of the church
2.Walk north and east

### Expected behavior

No freeze

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.5247 (22H2)
- Game Version: c36d390 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Hope [no_hope],
    Mind Over Matter [mindovermatter],
    Magiclysm [magiclysm],
    Bionic Slots [cbm_slots]
]

**Comment by harakka** [comment]
Looks like there's some massive files in the save so might be a runaway eoc again, but didn't have time to dissect properly yet.

**Comment by harakka** [comment]
Yeah EOC_IRON_ALLERGY_WEARING_STEEL_FOLLOWUP is there 20971520 times, that seems like it just might be a bug.

**Comment by RenechCDDA** [comment]
Uh yes, EOC runs itself. That is bad.

![image](https://github.com/user-attachments/assets/366ae3c5-5b60-4f88-a779-05c20396f1ac)

**Comment by RenechCDDA** [comment]
Dummied out the EOC and loaded the save. Extreme memory usage (peaking at 14GB during loading, sitting at *12GB* after loading 💦) but totally playable. The mentioned direction definitely has a NPC, as suspected. Walked towards them. Game froze when they entered the bubble, unfroze ~30 seconds later. Memory usage had dropped below 1GB.

So yeah, that EOC is definitely the culprit.

**Comment by Standing-Storm** [comment]
Hmm.  I'll see if a recurring EoC fixes the problem.

**Comment by harakka** [comment]
This should be fixed now after #78954, can you confirm? @kholat

**Comment by kholat** [comment]
For me on 2025-01-07-0609 it still freezes, I let it run for 20 mins and then killed it through task manager because its seemingly stuck.

**Comment by kholat** [comment]
Update: after letting run for an hour again, it did manage to unfreeze and the fix does work, so I'm closing this.
