### ISSUE TITLE
Good cooks using... "Unsavory" ingredients.

### ISSUE THREAD

**Issue by PGR-14** [CleverRaven/Cataclysm-DDA#79210]
### Is your feature request related to a problem? Please describe.

A lot of chefs know how to use spoiled/rotten food, & (probably) not giving everyone food poisoning. Mutant meat is also an issue, 'cause after a while, you ain't gonna be able to find that good veal. Regular survivors (As shown in the cooked versions) usually remove the obviously bad parts, but I bet a chef'd know what's wrong w/ it exactly, so they'd either toss it, or balance it out.

### Solution you would like.

3 "recipes":
- Scrap Soup: Use rotten/mutated ingredients in a soup. Mostly just dilutes the toxin, but it does decrease the amount of toxins in the food (By ~25%?).
- Bug Bisque: Lobster & Crab is essentially just water bugs, right? So why don't we make some bisque?
- Prepare mutant meat: Essentially converts it to regular meat at ~50% loss? Requires a fine cutting tool, & maybe a magnifying glass.

**Comment by Holli-Git** [comment]
Why would being good at cooking make you able to use rotten ingredients? 

I don't think removing toxins from mutant meat is be implemented either.

**Comment by PGR-14** [comment]
> Why would being good at cooking make you able to use rotten ingredients?
Basically, if you eat some food raw, you'll get aggressive bacteria in your stomach, but if you cook it (at the right temperature, for the right amount of time) it'll kill all the bacteria. A rotten/spoiled piece of food is when the bacteria has "digested" part of the food, & released toxins into it. Now, different foods have different bacteria, which releases different toxins, a good chef/survival expert will know how much will make you sick, so they dilute it accordingly.

Also, could be out of line, but all that rotten pasteurized milk (In sealed containers) is technically safe to eat. You will probably throw it up, but that's just because it tastes awful. It's essentially cheese (to the best of my knowledge).

> I don't think removing toxins from mutant meat is be implemented either.
Eh, fair enough

**Comment by PGR-14** [comment]
Done a bit of research, so far, mostly dilution & charcoal. Any way we could work w/ that?

**Comment by Maddremor** [comment]
The state of nascent decay that still isn't rotten proper is well covered by the `old` label, isn't it?

When it comes to mutant meat, the toxins are a non-specific mix of unhealthy chemicals and toxins, weird chiral hydrocarbons, and fun prions. You are explicitly not going to get rid of it.

**Comment by PGR-14** [comment]
Ope, forgot to close it. After doin' some research the answer is no.
